import "server-only";
import { generateText, isStepCount, NoSuchToolError, ToolLoopAgent } from "ai";
import { getDeepSeekModel } from "@/lib/ai/deepseek";
import { requireOwner } from "@/lib/auth/require-owner";
import { resolveAssistantPolicy } from "./policy";
import { buildAssistantTools } from "./tools";
import { selectAssistantModel, selectReasoningProviderOptionsForRequest } from "./model-router";
import { recordAgentStep, updateAgentRun } from "./persistence";
import { decideContextGate } from "./kernel/context-gate";
import { buildRootAgentPrompt } from "./kernel/prompt-builder";
import { createPrepareStep, initialToolNames } from "./kernel/prepare-step";
import { unknownToolError } from "./tools/registry";
import { buildAiExecutionContext, formatCurrentSurfaceForModel } from "./kernel/execution-context";
import { deriveSessionState } from "./kernel/session-state";
import type { AgentSessionState } from "./kernel/types";
import type { AssistantRequest, AssistantResult } from "./types";

function latestText(request:AssistantRequest) { const fromMessages=request.messages?.slice().reverse().find((message)=>message.role==="user")?.parts.filter((part)=>part.type==="text").map((part)=>part.text).join("\n"); return request.instruction?.trim()||fromMessages||"请帮助我分析当前内容。"; }
async function setup(request:AssistantRequest) {
  const {supabase,userId}=await requireOwner(); const {data:profile}=await supabase.from("profiles").select("timezone").eq("user_id",userId).maybeSingle(); const timezone=profile?.timezone||"Asia/Shanghai"; const message=latestText(request); const policy=resolveAssistantPolicy(request);
  let currentSurface=request.currentSurface?.content?{title:request.currentSurface.title,content:request.currentSurface.content}:null;
  if(!currentSurface&&request.currentEntity?.type==="note") { const {data:note}=await supabase.from("notes").select("title,body_markdown").eq("id",request.currentEntity.id).eq("status","active").is("deleted_at",null).is("archived_at",null).maybeSingle(); if(note) currentSurface={title:note.title,content:note.body_markdown.slice(0,20_000)}; }
  const executionContext=buildAiExecutionContext({currentSurface,requiresCurrentSurface:request.requiresCurrentSurface,usePersonalContext:request.usePersonalContext});
  const gate=decideContextGate({message,surface:request.surface,currentPath:request.currentPath,hasCurrentSurface:Boolean(currentSurface),requiresCurrentSurface:request.requiresCurrentSurface,usePersonalContext:request.usePersonalContext ?? (request.operation === "askNote" || request.operation === "deepThinkNote")});
  let previous:Partial<AgentSessionState>|null=null;
  if(request.runId) { const {data}=await supabase.from("agent_runs").select("kernel_state").eq("id",request.runId).eq("user_id",userId).maybeSingle(); previous=(data?.kernel_state as Partial<AgentSessionState>|null)??null; }
  const sessionState=deriveSessionState(previous,request.messages,gate); const selectedModel=selectAssistantModel({surface:request.surface,requestedModel:request.model,message,contextGate:gate}); const resolved=await getDeepSeekModel(userId,selectedModel);
  const system=`${buildRootAgentPrompt({timezone,sessionState,gateDecision:gate,currentSurfaceSummary:gate.needsCurrentSurface?formatCurrentSurfaceForModel(executionContext):null})}\n\nSURFACE_RULES\n${policy.instruction}`;
  if (process.env.NODE_ENV !== "production") console.info("[assistant-context]", { currentSurface: { included: Boolean(executionContext.currentSurface && gate.needsCurrentSurface), bodyChars: executionContext.currentSurface?.content.length ?? 0 }, personalContext: { enabled: executionContext.personalContextEnabled, items: 0 }, toolContext: { enabled: gate.needsTools } });
  const initial=gate.needsTools?initialToolNames(gate):[];
  if(request.runId) { await updateAgentRun({supabase,userId,runId:request.runId,status:"running",model:resolved.modelId,kernel:{contextMode:gate.mode,complexity:gate.complexity,initialModules:gate.likelyModules,activeSkills:sessionState.activeSkills,initialToolNames:initial,discoveredToolNames:sessionState.discoveredToolNames,sessionState}}); await recordAgentStep({supabase,userId,runId:request.runId,stepType:"context",title:gate.needsPersonalData?"已准备按需检索计划":"未访问 Personal OS",summary:gate.needsPersonalData?`模式 ${gate.mode}；初始模块 ${gate.likelyModules.join("、")||"无"}`:"普通问题直接回答",output:{contextMode:gate.mode,complexity:gate.complexity,initialModules:gate.likelyModules,activeSkills:sessionState.activeSkills,initialToolNames:initial,personalDataAccessed:false,osManifestChars:system.length,skillInstructionsChars:0,contextChars:0}}); }
  return {supabase,userId,timezone,policy,gate,sessionState,model:resolved.model,modelId:resolved.modelId,system,currentSurface,initial};
}
export async function createAssistantAgent(request:AssistantRequest) { const runtime=await setup(request); const allTools=runtime.gate.needsTools?buildAssistantTools({supabase:runtime.supabase,userId:runtime.userId,policy:{...runtime.policy,tools:["meta","context_read","reviews_read","briefing_read","search","calendar_read","calendar_proposal","todo_read","todo_proposal","inbox_proposal","notes_read","notes_proposal","career_read","career_proposal","memory_read","memory_proposal","projects_read","projects_proposal","files_read","shopping_read","shopping_proposal","travel_read","travel_proposal"]},timezone:runtime.timezone,runId:request.runId,onToolsDiscovered:(names)=>{runtime.sessionState.discoveredToolNames=[...new Set([...runtime.sessionState.discoveredToolNames,...names])]; if(request.runId) void runtime.supabase.from("agent_runs").update({kernel_state:runtime.sessionState,discovered_tool_names:runtime.sessionState.discoveredToolNames}).eq("id",request.runId).eq("user_id",runtime.userId);}}):{}; return {...runtime,agent:new ToolLoopAgent({model:runtime.model,stopWhen:isStepCount(runtime.gate.needsTools?runtime.policy.maxSteps:1),maxOutputTokens:runtime.policy.maxOutputTokens,providerOptions:selectReasoningProviderOptionsForRequest({surface:request.surface,mode:request.mode,operation:request.operation,contextGate:runtime.gate}),instructions:runtime.system,tools:allTools,prepareStep:runtime.gate.needsTools?createPrepareStep({decision:runtime.gate,sessionState:runtime.sessionState,initialToolNames:runtime.initial}):undefined,experimental_repairToolCall:async({error,toolCall})=>{if(NoSuchToolError.isInstance(error)){const detail=unknownToolError(toolCall.toolName,Object.keys(allTools));if(request.runId) await recordAgentStep({supabase:runtime.supabase,userId:runtime.userId,runId:request.runId,stepType:"error",title:"未注册工具调用被拒绝",summary:`${detail.requested} 不在当前 Tool Registry 中`,output:detail,status:"failed"});return null;}return null;}})}; }
export async function runAssistant(request:AssistantRequest):Promise<AssistantResult> { const runtime=await setup(request); const {text}=await generateText({model:runtime.model,maxOutputTokens:runtime.policy.maxOutputTokens,providerOptions:selectReasoningProviderOptionsForRequest({surface:request.surface,mode:request.mode,operation:request.operation,contextGate:runtime.gate}),system:runtime.system,prompt:latestText(request)}); await runtime.supabase.from("audit_logs").insert({user_id:runtime.userId,action:"assist",entity_type:request.currentEntity?.type||"assistant",entity_id:request.currentEntity?.id??null,actor_type:"user",after_data:{surface:request.surface,mode:request.mode,model:runtime.modelId,context_mode:runtime.gate.mode,personal_data_accessed:false,tool_names:[]}}); return {status:"success",text:text.trim(),modelId:runtime.modelId,contextSources:[]}; }
