import { CareerNav } from "@/components/career/career-nav";
import { PageHeader } from "@/components/shared/page-header";
import { requireOwner } from "@/lib/auth/require-owner";

type SearchRecord = { id: string; name?: string | null; content?: string | null; organization?: string | null; role?: string | null };
export default async function CareerSearch({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams; const query = q.trim().slice(0, 120); const results: Record<string, SearchRecord[]> = { Directions: [], Experiences: [], Facts: [], Outputs: [], Skills: [], Certifications: [] };
  if (query) { const { supabase } = await requireOwner(); const pattern = `%${query}%`; const [directions, experiences, facts, outputs, skills, certifications] = await Promise.all([supabase.from("career_directions").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10), supabase.from("experiences").select("id,organization,role").or(`organization.ilike.${pattern},role.ilike.${pattern}`).is("archived_at", null).limit(10), supabase.from("experience_facts").select("id,content").ilike("content", pattern).is("archived_at", null).limit(10), supabase.from("experience_outputs").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10), supabase.from("skills").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10), supabase.from("certifications").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10)]); results.Directions = directions.data ?? []; results.Experiences = experiences.data ?? []; results.Facts = facts.data ?? []; results.Outputs = outputs.data ?? []; results.Skills = skills.data ?? []; results.Certifications = certifications.data ?? []; }
  return <><PageHeader title="Career Search" description="仅检索当前所有者的职业数据。" /><CareerNav current="/career" /><form className="mb-8 flex gap-2"><input name="q" defaultValue={query} aria-label="搜索 Career" placeholder="名称、组织、岗位、事实或成果" className="w-full border bg-white px-3 py-2" /><button className="bg-[#365F78] px-3 py-2 text-sm text-white">搜索</button></form>{query ? <div className="space-y-6">{Object.entries(results).map(([label, records]) => <section key={label}><h2 className="font-medium">{label}</h2><div className="mt-2 divide-y border-y">{records.length ? records.map((record) => <p className="py-2 text-sm" key={record.id}>{record.name || record.content || `${record.organization ?? ""}${record.role ? ` · ${record.role}` : ""}`}</p>) : <p className="py-2 text-sm text-zinc-500">无结果</p>}</div></section>)}</div> : <p className="text-sm text-zinc-500">输入关键词开始搜索。</p>}</>;
}
