import { CareerNav } from "@/components/career/career-nav";
import { PageHeader } from "@/components/shared/page-header";
import { requireOwner } from "@/lib/auth/require-owner";

type SearchRecord = { id: string; name?: string | null; content?: string | null; organization?: string | null; role?: string | null };
export default async function CareerSearch({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams; const query = q.trim().slice(0, 120); const results: Record<string, SearchRecord[]> = { Directions: [], Experiences: [], Facts: [], Outputs: [], Skills: [], Certifications: [] };
  if (query) { const { supabase } = await requireOwner(); const pattern = `%${query}%`; const [directions, experiences, facts, outputs, skills, certifications] = await Promise.all([supabase.from("career_directions").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10), supabase.from("experiences").select("id,organization,role").or(`organization.ilike.${pattern},role.ilike.${pattern}`).is("archived_at", null).limit(10), supabase.from("experience_facts").select("id,content").ilike("content", pattern).is("archived_at", null).limit(10), supabase.from("experience_outputs").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10), supabase.from("skills").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10), supabase.from("certifications").select("id,name").ilike("name", pattern).is("archived_at", null).limit(10)]); results.Directions = directions.data ?? []; results.Experiences = experiences.data ?? []; results.Facts = facts.data ?? []; results.Outputs = outputs.data ?? []; results.Skills = skills.data ?? []; results.Certifications = certifications.data ?? []; }
  return <><PageHeader title="职业搜索" description="仅检索当前所有者的职业数据。" /><CareerNav current="/career" /><form className="mb-7 flex gap-2"><input name="q" defaultValue={query} aria-label="搜索 Career" placeholder="名称、组织、岗位、事实或成果" className="h-9 w-full rounded-[10px] border border-transparent bg-[var(--surface-control)] px-3 text-[13px] text-[var(--text-primary)] outline-none hover:bg-[var(--surface-control-hover)] focus:bg-[var(--surface-canvas)] focus:shadow-[0_0_0_2px_color-mix(in_srgb,var(--accent)_14%,transparent)]" /><button className="pressable h-9 rounded-[10px] bg-[var(--accent)] px-3.5 text-[13px] font-medium text-white hover:bg-[var(--accent-hover)] active:bg-[var(--accent-pressed)]">搜索</button></form>{query ? <div className="space-y-5">{Object.entries(results).map(([label, records]) => <section key={label}><h2 className="text-[13px] font-semibold text-[var(--text-primary)]">{label}</h2><div className="mt-2 divide-y divide-[var(--separator)] border-y border-[var(--separator)]">{records.length ? records.map((record) => <p className="py-2.5 text-[12.5px] text-[var(--text-primary)]" key={record.id}>{record.name || record.content || `${record.organization ?? ""}${record.role ? ` · ${record.role}` : ""}`}</p>) : <p className="py-2.5 text-[12.5px] text-[var(--text-tertiary)]">无结果</p>}</div></section>)}</div> : <p className="text-[12.5px] text-[var(--text-tertiary)]">输入关键词开始搜索。</p>}</>;
}
