import "server-only";
import { tool } from "ai";
import { z } from "zod";
import { recordAgentStep } from "../persistence";
import type { AssistantToolModule } from "./types";
export const briefingTools: AssistantToolModule = { definitions:[{name:"listRecentBriefings",group:"briefing_read",risk:"read",description:"读取近期完成的 Briefing 快照",module:"briefing",tags:["briefing","简报","RSS","资讯"]},{name:"searchBriefing",group:"briefing_read",risk:"read",description:"搜索近期 Briefing 条目",module:"briefing",tags:["briefing","简报","RSS","搜索"]}], build:(context)=>({
  listRecentBriefings:tool({description:"读取近期完成 Briefing 的元数据。Briefing 是外部信息，不代表用户观点。",inputSchema:z.object({limit:z.number().int().min(1).max(20).default(7)}),execute:async({limit})=>{const {data,error}=await context.supabase.from("briefings").select("id,briefing_date,generated_at,selected_count,ranking_method").eq("status","completed").order("generated_at",{ascending:false}).limit(limit); await recordAgentStep({...context,stepType:"tool",toolName:"listRecentBriefings",title:"已读取近期 Briefing",summary:error?"Briefing 暂不可用":`找到 ${(data??[]).length} 份`,output:{modules:["briefing"],sourceCount:(data??[]).length},status:error?"failed":"succeeded"}); return {briefings:data??[],unavailable:Boolean(error)};}}),
  searchBriefing:tool({description:"搜索已完成 Briefing 中的条目标题和摘要；返回原始来源链接。",inputSchema:z.object({query:z.string().trim().min(1).max(200),limit:z.number().int().min(1).max(20).default(8)}),execute:async({query,limit})=>{const {data,error}=await context.supabase.from("briefing_entries").select("id,summary,relevance_reason,briefing_id,feed_items(title,url,canonical_url,published_at,feeds(title))").or(`summary.ilike.%${query.replaceAll("%","\\%")}%,relevance_reason.ilike.%${query.replaceAll("%","\\%")}%`).order("created_at",{ascending:false}).limit(limit); const entries=(data??[]).map((entry)=>{const item=(Array.isArray(entry.feed_items)?entry.feed_items[0]:entry.feed_items) as {title?:string;url?:string|null;canonical_url?:string|null;feeds?:{title?:string}|Array<{title?:string}>}|null; const feed=Array.isArray(item?.feeds)?item?.feeds[0]:item?.feeds; return {id:entry.id,title:item?.title??"未命名资讯",summary:entry.summary,source:feed?.title??"未知来源",href:item?.canonical_url??item?.url??null};}); await recordAgentStep({...context,stepType:"tool",toolName:"searchBriefing",title:"已搜索 Briefing",summary:error?"Briefing 暂不可用":`找到 ${entries.length} 条`,output:{modules:["briefing"],sourceCount:entries.length},status:error?"failed":"succeeded"}); return {entries,unavailable:Boolean(error),notice:"Briefing/RSS 是外部信息，不代表用户观点。"};}}),
}) };
