import "server-only";
import { tool } from "ai";
import { z } from "zod";
import { searchPersonalOs } from "@/features/search/queries";
import type { SearchDomain } from "@/features/search/types";
import { personalOsModuleIds } from "../kernel/types";
import { recordAgentStep } from "../persistence";
import type { AssistantToolModule } from "./types";
const modules = z.enum(personalOsModuleIds);
const searchable = new Set<SearchDomain>(["notes","career","files","tasks","calendar","reviews","projects","shopping","travel"]);
export const contextTools: AssistantToolModule = { definitions:[
  {name:"inspectModule",group:"context_read",risk:"read",description:"读取一个 Personal OS 模块的紧凑摘要",module:"memory",tags:["context","模块","摘要","个人状态"]},
  {name:"getCurrentPersonalState",group:"context_read",risk:"read",description:"读取已确认 Memory、当前 Decision 与职业摘要",module:"memory",tags:["当前状态","个人情况","memory","career"]},
  {name:"searchPersonalContext",group:"context_read",risk:"read",description:"在指定 Personal OS 模块中搜索紧凑来源",module:"memory",tags:["context","搜索","个人记录"]},
], build:(context)=>({
  getCurrentPersonalState:tool({description:"读取紧凑的当前个人状态：已确认 Memory、active Decision 与职业摘要。不会读取历史 Notes、文件、日程或任务。",inputSchema:z.object({}),execute:async()=>{const [memories,decisions,career]=await Promise.all([context.supabase.from("personal_memories").select("id,memory_type,title,content,confirmed_at,updated_at").eq("status","active").neq("ai_visibility","never").is("archived_at",null).order("confirmed_at",{ascending:false}).limit(12),context.supabase.from("decisions").select("id,title,decision_markdown,status,decided_at,updated_at").eq("status","active").is("archived_at",null).limit(8),context.supabase.from("career_profiles").select("professional_headline,career_summary,current_stage,goals_markdown,constraints_markdown,updated_at").maybeSingle()]); const unavailable=Boolean(memories.error||decisions.error||career.error); await recordAgentStep({...context,stepType:"tool",toolName:"getCurrentPersonalState",title:"已读取当前个人状态",summary:unavailable?"当前状态暂不可用":`读取 ${(memories.data??[]).length} 条 Memory`,output:{modules:["memory","career"],sourceCount:(memories.data??[]).length+(decisions.data??[]).length+(career.data?1:0)},status:unavailable?"failed":"succeeded"}); return {memories:memories.data??[],decisions:decisions.data??[],career:career.data??null,unavailable};}}),
  inspectModule:tool({description:"读取一个模块的 summary 或 recent 摘要。严格限制数量；不能用它读取完整 Notes。",inputSchema:z.object({module:modules,depth:z.enum(["summary","recent"])}),execute:async({module,depth})=>{ let data:unknown=[]; let unavailable=false; if(module==="memory") { const result=await context.supabase.from("personal_memories").select("id,memory_type,title,content,confirmed_at,updated_at").eq("status","active").neq("ai_visibility","never").is("archived_at",null).order("updated_at",{ascending:false}).limit(depth==="recent"?12:6); data=result.data??[]; unavailable=Boolean(result.error); } else if(module==="career") { const result=await context.supabase.from("career_profiles").select("professional_headline,career_summary,current_stage,goals_markdown,constraints_markdown,updated_at").maybeSingle(); data=result.data??null; unavailable=Boolean(result.error); } else if(module==="projects") { const result=await context.supabase.from("projects").select("id,name,status,due_date,updated_at").is("archived_at",null).order("updated_at",{ascending:false}).limit(depth==="recent"?12:6); data=result.data??[]; unavailable=Boolean(result.error); } else { data={notice:`请使用 searchPersonalContext 在 ${module} 中按关键词检索。`}; } await recordAgentStep({...context,stepType:"tool",toolName:"inspectModule",title:`已查看 ${module}`,summary:unavailable?"模块暂不可用":"返回紧凑摘要",output:{modules:[module],unavailable},status:unavailable?"failed":"succeeded"}); return {module,depth,data,unavailable};}}),
  searchPersonalContext:tool({description:"在指定模块中搜索带标题、链接、时间和摘要的紧凑个人来源。",inputSchema:z.object({query:z.string().trim().min(1).max(220),modules:z.array(modules).max(6).optional(),limit:z.number().int().min(1).max(20).default(8),timeRange:z.object({from:z.string().datetime({offset:true}).optional(),to:z.string().datetime({offset:true}).optional()}).optional()}),execute:async({query,modules:requested,limit})=>{const selected=requested??["notes","career","memory"]; const base=selected.filter((item)=>searchable.has(item as SearchDomain)) as SearchDomain[]; const results=base.length?await searchPersonalOs({query,domains:base,limit}).catch(()=>[]):[]; const compact=results.map((item)=>({id:item.entityId,module:item.domain,title:item.title,href:item.href,timestamp:item.sourceUpdatedAt,excerpt:item.snippet,authority:item.domain==="notes"?"historical":"structured"})); await recordAgentStep({...context,stepType:"tool",toolName:"searchPersonalContext",title:"已搜索 Personal OS",summary:`找到 ${compact.length} 个来源`,input:{modules:selected,limit},output:{modules:selected,sourceIds:compact.map((item)=>item.id)},status:"succeeded"}); return {results:compact};}}),
}) };
