import { beforeEach, describe, expect, it, vi } from "vitest";
import { createHash } from "node:crypto";
const fake=vi.hoisted(()=>({owner:vi.fn(),read:vi.fn(),rpc:vi.fn()}));
vi.mock("@/lib/auth/require-owner",()=>({requireOwnerApi:fake.owner,apiAuthenticationFailure:(e:unknown)=>e==="unauthorized"?Response.json({}, {status:401}):null}));
vi.mock("@/lib/adapters/cloudflare-r2",()=>({r2BucketName:()=>"private",readR2ObjectStream:fake.read}));
import { GET, POST, PATCH } from "@/app/api/files/[documentId]/ocr/route";
const owner="11111111-1111-4111-8111-111111111111",id="22222222-2222-4222-8222-222222222222",token="33333333-3333-4333-8333-333333333333";
const bytes=Buffer.from("synthetic source"),sha=createHash("sha256").update(bytes).digest("hex");
let file:Record<string,unknown>,job:Record<string,unknown>|null;
const context={params:Promise.resolve({documentId:id})};
function from(table:string){const filters:Array<[string,unknown]>=[];const query={select:()=>query,eq:(k:string,v:unknown)=>{filters.push([k,v]);return query;},is:(k:string,v:unknown)=>{filters.push([k,v]);return query;},maybeSingle:async()=>{const row=table==="documents"?file:job;return{data:row&&filters.every(([k,v])=>row[k]===v)?row:null,error:null};}};return query;}
function request(method="GET",body?:object,source=false){return new Request(`https://fixture.test/api/files/${id}/ocr${source?"?source=1":""}`,{method,headers:{"Content-Type":"application/json","X-Ocr-Run":token},...(body?{body:JSON.stringify(body)}:{})});}
beforeEach(()=>{vi.clearAllMocks();file={id,user_id:owner,storage_provider:"cloudflare_r2",storage_bucket:"private",storage_state:"available",archived_at:null,storage_path:`${owner}/files/${id}/sealed.png`,checksum:sha,file_size:bytes.length,mime_type:"image/png",original_filename:"scan.png"};job={document_id:id,user_id:owner,source_path:file.storage_path,source_bucket:"private",source_checksum:sha,source_size:bytes.length,run_token:token,status:"processing",lease_expires_at:new Date(Date.now()+60000).toISOString(),pages_completed:0,page_count:null};fake.owner.mockResolvedValue({supabase:{from,rpc:fake.rpc},userId:owner});fake.rpc.mockResolvedValue({data:true,error:null});fake.read.mockImplementation(async()=>({size:bytes.length,body:new ReadableStream({start(c){c.enqueue(bytes);c.close();}})}));});
describe("private OCR API",()=>{
 it("authenticates before reading original bytes",async()=>{fake.owner.mockRejectedValue("unauthorized");expect((await GET(request("GET",undefined,true),context)).status).toBe(401);expect(fake.read).not.toHaveBeenCalled();});
 it("metadata GET never reads a document or runs recognition",async()=>{expect((await GET(request(),context)).status).toBe(200);expect(fake.read).not.toHaveBeenCalled();expect(fake.rpc).not.toHaveBeenCalled();});
 it.each([["user_id","other"],["storage_bucket","wrong"],["archived_at","now"],["storage_state","pending"]])("blocks unavailable %s",async(key,value)=>{file[key]=value;expect((await GET(request("GET",undefined,true),context)).status).toBe(409);expect(fake.read).not.toHaveBeenCalled();});
 it("requires active matching token and current source",async()=>{job!.run_token="other";expect((await GET(request("GET",undefined,true),context)).status).toBe(409);job!.run_token=token;job!.source_checksum="b".repeat(64);expect((await GET(request("GET",undefined,true),context)).status).toBe(409);expect(fake.read).not.toHaveBeenCalled();});
 it("returns private, checksum-verified bytes only",async()=>{const response=await GET(request("GET",undefined,true),context);expect(response.status).toBe(200);expect(response.headers.get("x-ocr-sha256")).toBe(sha);expect(response.headers.get("cache-control")).toContain("no-store");expect(response.headers.get("cross-origin-resource-policy")).toBe("same-origin");expect(await response.text()).toBe("synthetic source");});
 it("rejects corrupt R2 content without exposing provider errors",async()=>{fake.read.mockResolvedValue({size:bytes.length,body:new ReadableStream({start(c){c.enqueue(Buffer.alloc(bytes.length));c.close();}})});expect((await GET(request("GET",undefined,true),context)).status).toBe(409);fake.read.mockRejectedValue(new Error("private bucket secret"));expect(await(await GET(request("GET",undefined,true),context)).text()).not.toContain("secret");});
 it("starts only explicitly with authenticated owner derived by RPC",async()=>{fake.rpc.mockResolvedValue({data:[{run_token:token}],error:null});expect((await POST(request("POST"),context)).status).toBe(200);expect(fake.rpc).toHaveBeenCalledWith("start_document_ocr",{p_document_id:id});});
 it("rejects user_id and incomplete/oversized results",async()=>{expect((await PATCH(request("PATCH",{token,action:"complete",pages:1,total:2,text:"x",sha256:sha}),context)).status).toBe(400);expect((await PATCH(request("PATCH",{token,action:"cancel",user_id:owner}),context)).status).toBe(400);expect(fake.rpc).not.toHaveBeenCalled();});
 it("uses atomic source guards rather than unconditional document updates",async()=>{const response=await PATCH(request("PATCH",{token,action:"complete",pages:1,total:1,text:"中文 OCR",sha256:sha}),context);expect(response.status).toBe(200);expect(fake.rpc).toHaveBeenCalledWith("update_document_ocr",expect.objectContaining({p_run_token:token,p_document_id:id,p_text:"中文 OCR",p_sha256:sha}));fake.rpc.mockResolvedValue({data:false,error:null});expect((await PATCH(request("PATCH",{token,action:"cancel"}),context)).status).toBe(409);});
 it("rejects cross-origin mutations",async()=>{const req=new Request(`https://fixture.test/api/files/${id}/ocr`,{method:"POST",headers:{Origin:"https://unrelated.test"}});expect((await POST(req,context)).status).toBe(403);expect(fake.rpc).not.toHaveBeenCalled();});
});
