import { describe, expect, it } from "vitest";
import { contentHash, parseResearchImport } from "@/features/investment/import-contract";
import { investmentEntrySchema, RESEARCH_IMPORT_EXAMPLE } from "@/features/investment/schemas";
const example = JSON.parse(RESEARCH_IMPORT_EXAMPLE);
describe("investment imports", () => {
  it("accepts research without inventing performance", () => { const result = parseResearchImport(RESEARCH_IMPORT_EXAMPLE); expect(result.value.metrics).toBeNull(); expect(result.value.kind).toBe("research"); });
  it("rejects a plain research opinion dressed as a backtest", () => { expect(() => parseResearchImport(JSON.stringify({ ...example,kind:"backtest",metrics:{total_return_pct:"20",max_drawdown_pct:"10"} }))).toThrow(); });
  it("rejects fake verification statuses and performance on research", () => { expect(() => parseResearchImport(JSON.stringify({ ...example,verified:true }))).toThrow(); expect(() => parseResearchImport(JSON.stringify({ ...example,metrics:{total_return_pct:"20",max_drawdown_pct:"10"} }))).toThrow(); });
  it("requires reproducible backtest provenance and ordered dates", () => { const run = { ...example, kind:"backtest",metrics:{total_return_pct:"20",max_drawdown_pct:"10"},provenance:{...example.provenance,dataset_snapshot:"sha256:fixture",code_version:"test-commit",period_start:"2025-01-01",period_end:"2026-09-30",benchmark:"Test index",costs:"fees and slippage specified",artifact_url:"https://example.com/test-artifact"} }; expect(parseResearchImport(JSON.stringify(run)).value.kind).toBe("backtest"); expect(() => parseResearchImport(JSON.stringify({...run,provenance:{...run.provenance,period_end:"2026-10-06"}}))).toThrow(); });
  it("gives retries the same hash and conflicting content a different hash", () => { const first = parseResearchImport(RESEARCH_IMPORT_EXAMPLE); const reordered = Object.fromEntries(Object.entries(example).reverse()); expect(parseResearchImport(JSON.stringify(reordered)).hash).toBe(first.hash); expect(contentHash({...first.value,title:"changed"})).not.toBe(first.hash); });
  it("rejects non-http links and invalid dates", () => { expect(() => parseResearchImport(JSON.stringify({...example,source_urls:["javascript:alert(1)"]}))).toThrow(); expect(() => parseResearchImport(JSON.stringify({...example,as_of:"2026-02-30"}))).toThrow(); });
  it("rejects malformed and excessively large JSON", () => { expect(() => parseResearchImport("{" )).toThrow("JSON"); expect(() => parseResearchImport("x".repeat(120001))).toThrow("120 KB"); });
  it("requires explicit transaction confirmation and known execution prices", () => { const entry={account_id:"11111111-1111-4111-8111-111111111111",kind:"buy",symbol:"XSHG:TEST",occurred_on:"2026-01-01",quantity:"1",price:null,fees:"0",source:"fixture",import_key:"22222222-2222-4222-8222-222222222222",confirmed:true}; expect(investmentEntrySchema.safeParse(entry).success).toBe(false); expect(investmentEntrySchema.safeParse({...entry,kind:"opening"}).success).toBe(true); expect(investmentEntrySchema.safeParse({...entry,price:"1",confirmed:false}).success).toBe(false); });
});
