// @vitest-environment jsdom
import { act, createElement } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ complete: vi.fn(), reopen: vi.fn(), defer: vi.fn(), show: vi.fn(), todayInvalidate: vi.fn(), tasksInvalidate: vi.fn(), revalidate: vi.fn(), tasksMutate: vi.fn() }));
vi.mock("next/link", () => ({ default: ({ children, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) => createElement("a", props, children) }));
vi.mock("@/features/tasks/microsoft-todo", () => ({ completeMicrosoftTodoTaskAction: mocks.complete, reopenMicrosoftTodoTaskAction: mocks.reopen, deferMicrosoftTodoTaskAction: mocks.defer }));
vi.mock("@/components/shared/action-feedback", () => ({ useActionFeedback: () => ({ show: mocks.show }) }));
vi.mock("@/features/today/workspace-resource", () => ({ todayWorkspaceResource: { invalidate: mocks.todayInvalidate, revalidate: mocks.revalidate } }));
vi.mock("@/features/tasks/workspace-resource", () => ({ tasksWorkspaceResource: { invalidate: mocks.tasksInvalidate, mutate: mocks.tasksMutate } }));
import { CompleteTaskControl } from "@/components/today/complete-task-control";
import { DeferTaskControl, TodayTaskActions } from "@/components/today/today-task-actions";
let host: HTMLDivElement, root: Root;
beforeEach(() => { vi.resetAllMocks(); vi.stubGlobal("matchMedia", vi.fn(() => ({ matches: false }))); mocks.revalidate.mockResolvedValue({}); (globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; host = document.createElement("div"); document.body.append(host); root = createRoot(host); });
afterEach(async () => { await act(async () => root.unmount()); host.remove(); vi.unstubAllGlobals(); vi.useRealTimers(); delete (globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT; });
it("guards repeated completion, keeps failures retryable, and invalidates both caches after success", async () => {
  let finish!: () => void;
  mocks.complete.mockRejectedValueOnce(new Error("offline")).mockImplementationOnce(() => new Promise<void>((resolve) => { finish = resolve; }));
  await act(async () => root.render(createElement(CompleteTaskControl, { taskId: "t", title: "Task", compact: true })));
  const button = host.querySelector("button")!;
  await act(async () => button.click());
  expect(button.getAttribute("aria-label")).toBe("重试完成 Task");
  expect(mocks.show).toHaveBeenCalledWith(expect.objectContaining({ tone: "error", message: expect.stringContaining("未能确认") }));
  await act(async () => { button.click(); button.click(); });
  expect(mocks.complete).toHaveBeenCalledTimes(2);
  expect(button.disabled).toBe(true);
  await act(async () => finish());
  expect(mocks.tasksInvalidate).toHaveBeenCalledTimes(1);
  expect(mocks.todayInvalidate).toHaveBeenCalledTimes(1);
  expect(mocks.revalidate).toHaveBeenCalledWith({ force: true });
});
it("defers in the profile timezone and invalidates Tasks as well as Today", async () => {
  vi.useFakeTimers(); vi.setSystemTime(new Date("2026-03-07T17:00:00Z"));
  try {
    mocks.defer.mockResolvedValue(undefined);
    await act(async () => root.render(createElement(DeferTaskControl, { timezone: "America/New_York", task: { id: "t", title: "Task", due_at: null, importance: "normal", status: "notStarted" } })));
    await act(async () => [...host.querySelectorAll<HTMLButtonElement>("button")].find((button) => button.textContent?.includes("明天"))!.click());
    expect(mocks.defer.mock.calls[0][0].get("due_at")).toBe("2026-03-08T16:00:00.000Z");
    expect(mocks.tasksInvalidate).toHaveBeenCalledTimes(1);
    expect(mocks.todayInvalidate).toHaveBeenCalledTimes(1);
  } finally { vi.useRealTimers(); }
});

it("shows a success ring only after confirmation and lets it settle before Today revalidation", async () => {
  vi.useFakeTimers();
  let finish!: () => void;
  const onCompleted = vi.fn();
  mocks.complete.mockImplementationOnce(() => new Promise<void>((resolve) => { finish = resolve; }));
  await act(async () => root.render(createElement(CompleteTaskControl, { taskId: "t", title: "Task", status: "notStarted", compact: true, calm: true, onCompleted })));
  const button = host.querySelector("button")!;
  await act(async () => { button.click(); button.click(); });
  expect(mocks.complete).toHaveBeenCalledOnce();
  expect(host.querySelector(".today-task-completion")?.getAttribute("data-state")).toBe("pending");
  expect(host.querySelector<SVGElement>(".today-completion-check")?.style.opacity).toBe("0");
  expect(mocks.tasksMutate).not.toHaveBeenCalled();
  expect(mocks.show).not.toHaveBeenCalled();
  await act(async () => finish());
  expect(host.querySelector(".today-task-completion")?.getAttribute("data-state")).toBe("completed");
  expect(host.querySelector<SVGElement>(".today-completion-check")?.style.opacity).toBe("1");
  expect(mocks.todayInvalidate).not.toHaveBeenCalled();
  expect(mocks.show).toHaveBeenCalledWith(expect.objectContaining({ message: "已完成：Task", undo: expect.any(Function) }));
  await act(async () => vi.advanceTimersByTime(220));
  expect(mocks.todayInvalidate).toHaveBeenCalledOnce();
  expect(onCompleted).toHaveBeenCalledWith("t");
});
it("does not delay reduced motion or offer an inexact restore for other task statuses", async () => {
  vi.mocked(window.matchMedia).mockReturnValue({ matches: true } as MediaQueryList);
  mocks.complete.mockResolvedValue(undefined);
  const onCompleted = vi.fn();
  await act(async () => root.render(createElement(CompleteTaskControl, { taskId: "t", title: "Task", status: "inProgress", calm: true, onCompleted })));
  await act(async () => host.querySelector("button")!.click());
  expect(mocks.todayInvalidate).toHaveBeenCalledOnce();
  expect(onCompleted).toHaveBeenCalledWith("t");
  expect(mocks.show.mock.calls[0][0].undo).toBeUndefined();
});
it("restores only its own task after Undo and cancels a queued completion callback", async () => {
  vi.useFakeTimers();
  mocks.complete.mockResolvedValue(undefined); mocks.reopen.mockResolvedValue(undefined);
  const onCompleted = vi.fn();
  await act(async () => root.render(createElement(CompleteTaskControl, { taskId: "t", title: "Task", status: "notStarted", calm: true, onCompleted })));
  await act(async () => host.querySelector("button")!.click());
  const undo = mocks.show.mock.calls[0][0].undo;
  await act(async () => { undo(); undo(); });
  expect(mocks.reopen).toHaveBeenCalledOnce();
  expect(mocks.reopen.mock.calls[0][0].get("task_id")).toBe("t");
  const restored = mocks.tasksMutate.mock.calls[1][0]({ tasks: [{ id: "t", status: "completed" }, { id: "other", status: "completed" }] });
  expect(restored.tasks.map((task: { status: string }) => task.status)).toEqual(["notStarted", "completed"]);
  expect(host.querySelector(".today-task-completion")?.getAttribute("data-state")).toBe("idle");
  await act(async () => vi.advanceTimersByTime(220));
  expect(onCompleted).not.toHaveBeenCalled();
  expect(mocks.show).toHaveBeenLastCalledWith(expect.objectContaining({ message: "已恢复：Task" }));
});
it("keeps completion retryable without a success ring when the write is unconfirmed", async () => {
  mocks.complete.mockRejectedValue(new Error("offline"));
  await act(async () => root.render(createElement(CompleteTaskControl, { taskId: "t", title: "Task", calm: true })));
  await act(async () => host.querySelector("button")!.click());
  expect(host.querySelector(".today-task-completion")?.getAttribute("data-state")).toBe("failed");
  expect(host.querySelector<SVGElement>(".today-completion-check")?.style.opacity).toBe("0");
  expect(host.querySelector("button")!.disabled).toBe(false);
  expect(mocks.tasksMutate).not.toHaveBeenCalled();
});
it("keeps postpone in a named task sheet with close and focus restoration", async () => {
  await act(async () => root.render(createElement(TodayTaskActions, { timezone: "Asia/Shanghai", task: { id: "t", title: "Task", due_at: null, importance: "normal", status: "notStarted" } })));
  const trigger = host.querySelector<HTMLButtonElement>('[aria-label="更多操作：Task"]')!;
  expect(host.textContent).not.toContain("明天");
  trigger.focus();
  await act(async () => trigger.click());
  const dialog = document.querySelector<HTMLElement>('[role="dialog"]')!;
  expect(document.getElementById(dialog.getAttribute("aria-labelledby")!)?.textContent).toBe("Task");
  expect(document.activeElement).toBe(dialog.querySelector('[data-slot="sheet-title"]'));
  expect(dialog.querySelector('a[href="/tasks?task=t"]')).not.toBeNull();
  expect(dialog.textContent).toContain("延后到明天");
  await act(async () => dialog.querySelector<HTMLButtonElement>('[aria-label="关闭任务操作"]')!.click());
  expect(document.querySelector('[role="dialog"]')).toBeNull();
  expect(document.activeElement).toBe(trigger);
  expect(mocks.defer).not.toHaveBeenCalled();
});
it("blocks dismissal and repeated postpone writes until the result is known", async () => {
  let finish!: () => void;
  mocks.defer.mockImplementationOnce(() => new Promise<void>((resolve) => { finish = resolve; }));
  await act(async () => root.render(createElement(TodayTaskActions, { timezone: "Asia/Shanghai", task: { id: "t", title: "Task", due_at: null, importance: "normal", status: "notStarted" } })));
  await act(async () => host.querySelector("button")!.click());
  const dialog = document.querySelector<HTMLElement>('[role="dialog"]')!;
  const defer = dialog.querySelector<HTMLButtonElement>('[aria-label="延后到明天 Task"]')!;
  await act(async () => { defer.click(); defer.click(); });
  expect(mocks.defer).toHaveBeenCalledOnce();
  expect(dialog.querySelector<HTMLButtonElement>('[aria-label="关闭任务操作"]')!.disabled).toBe(true);
  await act(async () => document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true })));
  expect(document.querySelector('[role="dialog"]')).not.toBeNull();
  await act(async () => finish());
  expect(document.querySelector('[role="dialog"]')).toBeNull();
});
it("keeps a failed restore visibly completed until a fresh read confirms the result", async () => {
  vi.useFakeTimers();
  mocks.complete.mockResolvedValue(undefined); mocks.reopen.mockRejectedValue(new Error("offline"));
  await act(async () => root.render(createElement(CompleteTaskControl, { taskId: "t", title: "Task", status: "notStarted", calm: true })));
  await act(async () => host.querySelector("button")!.click());
  await act(async () => mocks.show.mock.calls[0][0].undo());
  expect(host.querySelector(".today-task-completion")?.getAttribute("data-state")).toBe("completed");
  expect(mocks.tasksMutate).toHaveBeenCalledOnce();
  expect(mocks.show).toHaveBeenLastCalledWith(expect.objectContaining({ tone: "error", message: expect.stringContaining("恢复结果") }));
  expect(mocks.revalidate).toHaveBeenCalledWith({ force: true });
  await act(async () => vi.advanceTimersByTime(220));
});
it("retains the task sheet and unlocks retry after an unconfirmed postpone", async () => {
  mocks.defer.mockRejectedValueOnce(new Error("offline")).mockResolvedValueOnce(undefined);
  await act(async () => root.render(createElement(TodayTaskActions, { timezone: "Asia/Shanghai", task: { id: "t", title: "Task", due_at: null, importance: "normal", status: "notStarted" } })));
  await act(async () => host.querySelector("button")!.click());
  await act(async () => document.querySelector<HTMLButtonElement>('[aria-label="延后到明天 Task"]')!.click());
  const dialog = document.querySelector<HTMLElement>('[role="dialog"]')!;
  expect(dialog.querySelector('[role="alert"]')?.textContent).toContain("任务仍保留");
  expect(dialog.querySelector<HTMLButtonElement>('[aria-label="关闭任务操作"]')!.disabled).toBe(false);
  expect(mocks.tasksMutate).not.toHaveBeenCalled();
  await act(async () => dialog.querySelector<HTMLButtonElement>('[aria-label="重试延后 Task"]')!.click());
  expect(mocks.defer).toHaveBeenCalledTimes(2);
  expect(document.querySelector('[role="dialog"]')).toBeNull();
});
