import { notFound } from "next/navigation";
import { NoteEditor } from "@/components/notes/note-editor";
import { NoteDocumentShell } from "@/components/notes/note-document-shell";
import { FolderPicker } from "@/components/notes/folder-picker";
import { getActiveNoteFolders, getNote } from "@/features/notes/queries";
import { getAiSettings } from "@/features/ai/queries";
import { archiveNote, createNoteVersion, moveNote, restoreNoteVersion, trashNote } from "@/features/notes/actions";

export default async function NotePage({ params }: { params: Promise<{ noteId: string }> }) {
  const { noteId } = await params;
  const data = await getNote(noteId);
  if (!data) notFound();
  const folders = await getActiveNoteFolders();
  const ai = await getAiSettings();
  const inspector = <div className="text-sm">{data.state === "base" ? <p className="mb-5 border-l-2 border-amber-600 bg-amber-50 px-3 py-2 text-xs text-amber-800">当前为兼容模式；链接和完整版本功能待 migration 应用后启用。</p> : null}<section><h2 className="text-xs font-medium text-[var(--text-tertiary)]">文件夹</h2><form action={moveNote} className="mt-2 grid gap-2"><input type="hidden" name="note_id" value={data.note.id} /><FolderPicker folders={folders} initialFolderId={data.note.folder_id ?? null} idPrefix={`detail-${data.note.id}`} /><button className="justify-self-start text-xs text-[var(--accent)] hover:underline">移动笔记</button></form></section><section className="mt-7"><h2 className="text-xs font-medium text-[var(--text-tertiary)]">Links</h2><p className="mt-2 text-[var(--text-secondary)]">已解析 {data.links.filter((link) => link.target_note_id).length} · 未解析 {data.links.filter((link) => !link.target_note_id).length}</p></section><section className="mt-7"><h2 className="text-xs font-medium text-[var(--text-tertiary)]">Backlinks</h2><p className="mt-2 text-[var(--text-secondary)]">{data.backlinks.length ? `被 ${data.backlinks.length} 篇笔记引用` : "暂无反向链接"}</p></section><section className="mt-7"><h2 className="text-xs font-medium text-[var(--text-tertiary)]">Versions</h2><form action={createNoteVersion} className="mt-2"><input type="hidden" name="note_id" value={data.note.id} /><button className="text-xs text-[var(--accent)] hover:underline">创建版本</button></form><div className="mt-3 space-y-2 text-xs text-[var(--text-secondary)]">{data.versions.map((version) => <form action={restoreNoteVersion} key={version.id} className="flex gap-2"><span>v{version.version_number} · {version.reason}</span><input type="hidden" name="note_id" value={data.note.id} /><input type="hidden" name="version_id" value={version.id} /><button className="text-[var(--accent)]">恢复</button></form>)}</div></section><details className="mt-8 border-t pt-4"><summary className="cursor-pointer text-xs font-medium text-[var(--text-tertiary)]">Advanced</summary><a className="mt-4 block text-[var(--accent)]" href={`/api/exports/notes/${data.note.id}`}>下载 Markdown</a><form action={archiveNote} className="mt-4"><input type="hidden" name="note_id" value={data.note.id} /><button className="text-[var(--text-secondary)] hover:text-[var(--text-primary)]">归档</button></form><form action={trashNote} className="mt-3"><input type="hidden" name="note_id" value={data.note.id} /><button className="text-[var(--danger)]">移入回收站</button></form></details></div>;
  return <NoteDocumentShell noteId={data.note.id} editor={<NoteEditor note={data.note} noteAiDefaultModel={ai.settings?.model === "deepseek-v4-pro" ? "deepseek-v4-pro" : "deepseek-v4-flash"} />} inspector={inspector} />;
}
