"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireOwner } from "@/lib/auth/require-owner";
import { contentHash, parseWikiLinks } from "./utils";
const noteSchema = z.object({ noteId: z.string().uuid().optional(), expectedRevision: z.coerce.number().int().min(0), title: z.string().max(240), bodyMarkdown: z.string().max(200000) });
const folderSchema = z.object({ name: z.string().trim().min(1).max(120), parentId: z.string().uuid().nullable().optional() });
function fail(): never { throw new Error("操作未能完成，请检查输入、权限或网络后重试。"); }
async function audit(supabase: Awaited<ReturnType<typeof requireOwner>>["supabase"], userId: string, action: string, id: string, data: Record<string, unknown>) { const { error } = await supabase.from("audit_logs").insert({ user_id: userId, action, entity_type: "note", entity_id: id, actor_type: "user", after_data: data }); if (error) fail(); }
export async function createNote() { const { supabase, userId } = await requireOwner(); const title = "无标题笔记"; const body = ""; const hash = contentHash(body); const { data, error } = await supabase.from("notes").insert({ user_id: userId, title, body_markdown: body, status: "active", revision: 1, content_hash: hash, word_count: 0, character_count: 0, last_saved_at: new Date().toISOString() }).select("id").single(); if (error) fail(); const version = await supabase.from("note_versions").insert({ user_id: userId, note_id: data.id, title, body_markdown: body, version_number: 1, created_by: userId, content_hash: hash, revision: 1, reason: "initial" }); if (version.error) fail(); await audit(supabase, userId, "create", data.id, { revision: 1 }); redirect(`/notes/${data.id}`); }
export async function saveNote(input: unknown) { const { supabase, userId } = await requireOwner(); const parsed = noteSchema.safeParse(input); if (!parsed.success || !parsed.data.noteId) fail(); const value = parsed.data; const hash = contentHash(value.bodyMarkdown); const words = value.bodyMarkdown.trim() ? value.bodyMarkdown.trim().split(/\s+/).length : 0; const now = new Date().toISOString(); const { data, error } = await supabase.from("notes").update({ title: value.title || "无标题笔记", body_markdown: value.bodyMarkdown, content_hash: hash, word_count: words, character_count: value.bodyMarkdown.length, last_saved_at: now, revision: value.expectedRevision + 1 }).eq("id", value.noteId).eq("revision", value.expectedRevision).select("id,revision").maybeSingle(); if (error) fail(); if (!data) return { status: "conflict" as const }; const links = parseWikiLinks(value.bodyMarkdown); await supabase.from("note_links").delete().eq("source_note_id", value.noteId); if (links.length) { const titles = [...new Set(links.map((link) => link.targetTitle))]; const { data: targets } = await supabase.from("notes").select("id,title").in("title", titles).is("deleted_at", null); const map = new Map((targets ?? []).map((target) => [target.title, target.id])); const insert = await supabase.from("note_links").insert(links.map((link) => ({ user_id: userId, source_note_id: value.noteId!, target_note_id: map.get(link.targetTitle) ?? null, target_title: link.targetTitle, alias: link.alias, link_type: "wiki", position_start: link.start, position_end: link.end }))); if (insert.error) fail(); }
  revalidatePath(`/notes/${value.noteId}`); revalidatePath("/notes"); return { status: "saved" as const, revision: data.revision, lastSavedAt: now };
}
export async function createFolder(formData: FormData) { const { supabase, userId } = await requireOwner(); const raw = Object.fromEntries(formData); const parsed = folderSchema.safeParse({ name: raw.name, parentId: raw.parent_id || null }); if (!parsed.success) fail(); if (parsed.data.parentId) { const { data } = await supabase.from("note_folders").select("id").eq("id", parsed.data.parentId).maybeSingle(); if (!data) fail(); } const { error } = await supabase.from("note_folders").insert({ user_id: userId, name: parsed.data.name, parent_id: parsed.data.parentId ?? null }); if (error) fail(); revalidatePath("/notes"); }
export async function trashNote(formData: FormData) { const { supabase, userId } = await requireOwner(); const id = String(formData.get("note_id") || ""); const { data, error } = await supabase.from("notes").update({ status: "trashed", deleted_at: new Date().toISOString() }).eq("id", id).select("id").maybeSingle(); if (error || !data) fail(); await audit(supabase, userId, "trash", id, {}); revalidatePath("/notes"); redirect("/notes"); }
