import Link from "next/link";
import { PageHeader } from "@/components/shared/page-header";
import { CareerNav, CareerOpportunityNav } from "@/components/career/career-nav";
import { CareerForm } from "@/components/career/career-form";
import { Field, PrimaryButton, SelectField, TextField } from "@/components/career/form-controls";
import { submitCareerForm } from "@/features/career/form-actions";
import { getOpportunities } from "@/features/career/queries";

const statusLabels: Record<string, string> = { watching: "关注", researching: "研究中", preparing: "准备中", closed: "已结束" };
const assessmentLabels: Record<string, string> = { supported: "已有支持", partial: "部分支持", gap: "需要补充", unknown: "待判断", strong: "充分支持", weak: "支持较弱", missing: "缺少支持" };
const requirementOptions = [{ value: "must_have", label: "必须" }, { value: "preferred", label: "优先" }, { value: "responsibility", label: "职责" }, { value: "skill", label: "技能" }, { value: "experience", label: "经历" }, { value: "credential", label: "证书" }, { value: "other", label: "其他" }];
const summaryClass = "inline-flex min-h-11 cursor-pointer list-none items-center text-[13px] font-medium text-[var(--accent)]";

export default async function OpportunitiesPage() {
  const data = await getOpportunities();
  const buckets = [["正在关注", data.opportunities.filter((item) => item.status !== "closed" && (!item.deadline_at || item.deadline_at >= data.now))], ["已截止或结束", data.opportunities.filter((item) => item.status === "closed" || (item.deadline_at && item.deadline_at < data.now))]] as const;
  return <>
    <PageHeader title="机会与申请" description="从真实岗位开始，连接准备材料、申请记录与面试。"/>
    <CareerNav current="/career/opportunities"/>
    <CareerOpportunityNav current="opportunities"/>
    {data.unavailable ? <p role="alert" className="mb-6 text-[13px] text-[var(--danger)]">部分机会数据暂时不可用，请稍后刷新。</p> : null}
    <details className="mb-8"><summary className={summaryClass}>＋ 新建机会</summary><CareerForm action={submitCareerForm.bind(null, "createOpportunity")} resetOnSuccess className="mt-3 grid gap-4 rounded-[var(--radius-lg)] bg-[var(--surface-hover)] p-4 md:grid-cols-3" successTargetId="opportunity-list" successMessage="机会已保存，可在下方查看。">
      <Field name="organization" label="组织 *" required/><Field name="role_title" label="岗位 *" required/><SelectField name="opportunity_type" label="类型" values={[{ value: "internship", label: "实习" }, { value: "full_time", label: "全职" }, { value: "graduate_program", label: "校招项目" }, { value: "research", label: "研究" }, { value: "other", label: "其他" }]}/>
      <Field name="location" label="地点"/><Field name="work_mode" label="办公方式"/><Field name="deadline_at" label="截止时间" type="datetime-local"/><Field name="source_name" label="来源"/><Field name="source_url" label="来源链接" type="url"/><SelectField name="status" label="状态" values={[{ value: "watching", label: "关注" }, { value: "researching", label: "研究中" }, { value: "preparing", label: "准备中" }]}/><div className="md:col-span-3"><TextField name="jd_markdown" label="JD / 机会描述"/></div><input type="hidden" name="career_direction_id" value=""/><input type="hidden" name="compensation_text" value=""/><input type="hidden" name="recruitment_cycle" value=""/><input type="hidden" name="expected_start_date" value=""/><input type="hidden" name="notes_markdown" value=""/><PrimaryButton>保存机会</PrimaryButton>
    </CareerForm></details>

    <div id="opportunity-list" className="space-y-9 scroll-mt-24">{buckets.map(([title, opportunities]) => opportunities.length ? <section key={title}><h2 className="text-[13px] font-medium text-[var(--text-secondary)]">{title} · {opportunities.length}</h2><div className="mt-3 divide-y divide-[var(--separator)] border-y border-[var(--separator)]">{opportunities.map((opportunity) => {
      const requirements = data.requirements.filter((item) => item.opportunity_id === opportunity.id);
      const latestRun = data.gaps.find((run) => run.opportunity_id === opportunity.id);
      const gapItems = latestRun ? data.gapItems.filter((item) => item.run_id === latestRun.id) : [];
      return <details key={opportunity.id} id={`opportunity-${opportunity.id}`} className="group scroll-mt-24 py-4"><summary className="flex min-h-11 cursor-pointer list-none flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="text-[15px] font-medium text-[var(--text-primary)]">{opportunity.role_title}</h3><p className="mt-1 text-[13px] text-[var(--text-secondary)]">{opportunity.organization}{opportunity.location ? ` · ${opportunity.location}` : ""}</p></div><div className="text-[12px] leading-6 text-[var(--text-secondary)]"><p>{statusLabels[opportunity.status] ?? opportunity.status}</p><p className="tabular-nums">{opportunity.deadline_at ? `${new Date(opportunity.deadline_at).toLocaleString("zh-CN", { dateStyle: "medium", timeStyle: "short" })} 截止` : "未设截止时间"}</p></div></summary>
        <div className="mt-4 border-t border-[var(--separator)] pt-4">
          <div className="mb-6 flex flex-wrap items-start gap-3"><Link href={`/career/applications?opportunity=${opportunity.id}#create-application`} className="inline-flex min-h-11 items-center rounded-[var(--radius-md)] bg-[var(--accent)] px-4 text-[13px] font-medium text-white hover:opacity-90">创建申请</Link><CareerForm action={submitCareerForm.bind(null, "prepareOpportunityInterview")}><input type="hidden" name="opportunity_id" value={opportunity.id}/><button className="min-h-11 rounded-[var(--radius-md)] bg-[var(--surface-hover)] px-4 text-[13px] font-medium text-[var(--text-primary)]">准备面试 →</button></CareerForm></div>
          {opportunity.jd_markdown ? <details className="mb-5"><summary className={summaryClass}>查看原始岗位描述</summary><p className="mt-2 whitespace-pre-wrap text-[14px] leading-7 text-[var(--text-secondary)]">{opportunity.jd_markdown}</p></details> : null}
          <div className="grid gap-8 lg:grid-cols-2"><section><h4 className="text-[14px] font-semibold">岗位要求</h4><div className="mt-3 space-y-3">{requirements.map((requirement) => <div key={requirement.id} className="text-[14px] leading-7"><p>{requirement.requirement_text}</p><p className="text-[12px] text-[var(--text-secondary)]">{requirement.importance === "high" ? "重要 · " : ""}{requirementOptions.find((option) => option.value === requirement.requirement_type)?.label ?? "其他"}</p></div>)}{!requirements.length ? <p className="text-[13px] leading-6 text-[var(--text-secondary)]">还没有岗位要求，从 JD 中添加一条真实要求。</p> : null}</div>
            <details className="mt-3"><summary className={summaryClass}>＋ 添加要求</summary><CareerForm action={submitCareerForm.bind(null, "createOpportunityRequirement")} resetOnSuccess className="mt-2 grid gap-4 rounded-[var(--radius-lg)] bg-[var(--surface-hover)] p-4 sm:grid-cols-2"><input type="hidden" name="opportunity_id" value={opportunity.id}/><SelectField name="requirement_type" label="类型" values={requirementOptions}/><SelectField name="importance" label="重要性" values={[{ value: "normal", label: "普通" }, { value: "high", label: "高" }, { value: "low", label: "低" }]}/><div className="sm:col-span-2"><TextField name="requirement_text" label="要求 *"/></div><input type="hidden" name="source_excerpt" value=""/><input type="hidden" name="extraction_source" value="human"/><PrimaryButton>添加要求</PrimaryButton></CareerForm></details>
          </section><section><h4 className="text-[14px] font-semibold">准备缺口</h4>{latestRun ? <div className="mt-3"><p className="text-[14px] leading-7 text-[var(--text-secondary)]">{latestRun.summary}</p><div className="mt-3 space-y-3">{gapItems.map((item) => { const requirement = Array.isArray(item.opportunity_requirements) ? item.opportunity_requirements[0] : item.opportunity_requirements; return <div key={item.id} className="border-l-2 border-[var(--separator)] pl-3"><p className="text-[14px] leading-6">{requirement?.requirement_text}</p><p className="mt-1 text-[13px] leading-6 text-[var(--text-secondary)]">{assessmentLabels[item.assessment] ?? item.assessment} · {item.explanation}</p></div>; })}</div></div> : <p className="mt-3 text-[13px] leading-6 text-[var(--text-secondary)]">添加岗位要求后，可对照职业事实或简历，判断还需补充的内容。</p>}
            <details className="mt-3"><summary className={summaryClass}>分析准备情况</summary><p className="mb-3 text-[12px] leading-6 text-[var(--text-secondary)]">仅引用职业事实、已批准表达、技能、证书与成果；笔记不会直接作为能力证明。</p><div className="space-y-3"><CareerForm action={submitCareerForm.bind(null, "runGapAnalysis")}><input type="hidden" name="opportunity_id" value={opportunity.id}/><input type="hidden" name="analysis_type" value="capital"/><input type="hidden" name="resume_version_id" value=""/><button disabled={!requirements.length} className="min-h-11 rounded-[var(--radius-md)] bg-[var(--surface-hover)] px-3 text-[13px] disabled:opacity-40">分析职业资本</button></CareerForm><CareerForm action={submitCareerForm.bind(null, "runGapAnalysis")} className="flex flex-wrap items-end gap-3"><input type="hidden" name="opportunity_id" value={opportunity.id}/><input type="hidden" name="analysis_type" value="resume"/><SelectField name="resume_version_id" label="选择简历版本" values={[{ value: "", label: "选择简历" }, ...data.resumes.map((resume) => ({ value: resume.id, label: resume.title }))]}/><button disabled={!requirements.length || !data.resumes.length} className="min-h-11 rounded-[var(--radius-md)] bg-[var(--surface-hover)] px-3 text-[13px] disabled:opacity-40">分析简历</button></CareerForm></div></details>
          </section></div>
        </div>
      </details>;
    })}</div></section> : null)}{!data.opportunities.length ? <div className="py-14"><h2 className="text-[15px] font-medium">还没有机会</h2><p className="mt-2 text-[14px] leading-7 text-[var(--text-secondary)]">从上方新建一个真实岗位，再继续准备与申请。</p></div> : null}</div>
  </>;
}
