import Link from "next/link";
import { FolderPicker } from "@/components/notes/folder-picker";
import { createFolder, createNoteInFolder, deleteEmptyFolder, moveNote, openDailyNote, renameNote } from "@/features/notes/actions";
import { getNotesWorkspace } from "@/features/notes/queries";
import { formatNoteTimestamp } from "@/features/notes/utils";

type Folder = { id: string; name: string; parent_id: string | null };
type Note = { id: string; title: string; updated_at: string; pinned_at: string | null; folder_id: string | null };

function FolderTree({ folders, notes, parentId, selectedId, depth = 0 }: { folders: Folder[]; notes: Note[]; parentId: string | null; selectedId: string | null; depth?: number }) {
  return folders.filter((folder) => folder.parent_id === parentId).map((folder) => {
    const count = notes.filter((note) => note.folder_id === folder.id).length;
    return <div key={folder.id}><Link href={`/notes?folder=${folder.id}`} className={`flex items-center justify-between rounded px-2 py-1.5 text-sm ${selectedId === folder.id ? "bg-[#EDF3F6] text-[#365F78]" : "text-zinc-700 hover:bg-white"}`} style={{ marginLeft: `${depth * 12}px` }}><span className="min-w-0 truncate">⌁ {folder.name}</span><span className="font-mono text-[11px] text-zinc-400">{count}</span></Link><FolderTree folders={folders} notes={notes} parentId={folder.id} selectedId={selectedId} depth={depth + 1} /></div>;
  });
}

export default async function Notes({ searchParams }: { searchParams: Promise<{ folder?: string; daily?: string }> }) {
  const { notes, folders, timezone, state } = await getNotesWorkspace();
  const { folder: requestedFolder, daily } = await searchParams;
  const selectedFolder = folders.find((folder) => folder.id === requestedFolder) ?? null;
  const visibleNotes = selectedFolder ? notes.filter((note) => note.folder_id === selectedFolder.id) : notes;

  return <section className="max-w-5xl"><header className="flex flex-wrap items-start justify-between gap-4 border-b pb-6"><div><p className="text-xs font-medium tracking-wide text-zinc-500">KNOWLEDGE BASE</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Notes</h1><p className="mt-1 text-sm text-zinc-500">原始 Markdown 是正文的唯一权威格式。</p></div><div className="flex gap-2"><form action={openDailyNote}><button className="border bg-white px-3 py-2 text-sm text-[#365F78] hover:bg-[#EDF3F6]">今日日记</button></form><form action={createNoteInFolder}><input type="hidden" name="folder_id" value={selectedFolder?.id ?? ""} /><button className="bg-[#365F78] px-3 py-2 text-sm text-white">新建笔记</button></form></div></header>
    {state === "base" ? <p role="status" className="mt-5 border-l-2 border-amber-600 bg-amber-50 px-3 py-2 text-sm text-amber-800">笔记基础功能正在使用兼容模式：新建、编辑和日记均可用；文件夹、回收站和链接需要应用 Notes Workspace migration 后启用。</p> : null}
    {state === "unavailable" ? <p role="alert" className="mt-5 border-l-2 border-red-700 bg-red-50 px-3 py-2 text-sm text-red-800">暂时无法读取笔记库。请检查 Supabase 环境变量、登录状态和数据库连接。</p> : null}
    {daily === "error" ? <p role="alert" className="mt-5 border-l-2 border-red-700 bg-red-50 px-3 py-2 text-sm text-red-800">今日日记暂时未能创建或归位。请刷新页面后重试；已有日记不会被删除。</p> : null}
    <div className="mt-6 grid gap-8 lg:grid-cols-[360px_minmax(0,520px)]"><aside className="border-r pr-7"><div className="flex items-center justify-between"><h2 className="text-xs font-medium tracking-wide text-zinc-500">文件夹</h2><Link href="/notes" className="text-xs text-[#365F78]">全部 {notes.length}</Link></div>{state === "ready" ? <form action={createFolder} className="mt-3 grid gap-2"><input name="name" required aria-label="文件夹名称" placeholder="新建文件夹" className="min-w-0 border bg-white px-2 py-1.5 text-sm" /><select name="parent_id" className="border bg-white px-2 py-1.5 text-xs"><option value="">根目录</option>{folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><button className="justify-self-start border px-2 py-1 text-xs">添加文件夹</button></form> : null}<nav className="mt-4 border-l pl-2"><Link href="/notes" className={`flex items-center justify-between rounded px-2 py-1.5 text-sm ${!selectedFolder ? "bg-[#EDF3F6] text-[#365F78]" : "text-zinc-700 hover:bg-white"}`}><span>⌂ 所有笔记</span><span className="font-mono text-[11px] text-zinc-400">{notes.length}</span></Link><FolderTree folders={folders} notes={notes} parentId={null} selectedId={selectedFolder?.id ?? null} /></nav><Link href="/notes/trash" className="mt-5 block text-sm text-zinc-500 hover:text-[#365F78]">回收站</Link></aside>
      <main className="min-w-0 max-w-[520px]"><div className="flex flex-wrap items-baseline justify-between gap-2 border-b pb-3"><div><h2 className="font-medium">{selectedFolder ? selectedFolder.name : "全部笔记"}</h2><p className="mt-1 text-xs text-zinc-500">{visibleNotes.length} 篇 · 最近更新优先</p></div><form action={createNoteInFolder}><input type="hidden" name="folder_id" value={selectedFolder?.id ?? ""} /><button className="text-sm text-[#365F78]">在此处新建 →</button></form></div>{selectedFolder && visibleNotes.length === 0 && !folders.some((folder) => folder.parent_id === selectedFolder.id) ? <form action={deleteEmptyFolder} className="mt-3"><input type="hidden" name="folder_id" value={selectedFolder.id} /><button className="text-xs text-zinc-500 underline underline-offset-2 hover:text-red-700">删除此空文件夹</button></form> : null}{visibleNotes.length ? <div className="divide-y">{visibleNotes.map((note) => <article key={note.id} className="py-3"><Link className="group flex items-center justify-between gap-4 hover:text-[#365F78]" href={`/notes/${note.id}`}><div className="min-w-0"><p className="truncate text-sm font-medium">{note.title || "无标题笔记"}</p><p className="mt-1 text-xs text-zinc-400">{note.pinned_at ? "已固定 · " : ""}{formatNoteTimestamp(note.updated_at, timezone)}</p></div><span className="text-sm text-zinc-300 group-hover:text-[#365F78]">→</span></Link><details className="mt-2"><summary className="w-fit cursor-pointer text-xs text-zinc-500 hover:text-[#365F78]">整理此笔记</summary><div className="mt-2 grid gap-2 border-l pl-3"><form action={renameNote} className="flex gap-2"><input type="hidden" name="note_id" value={note.id} /><input name="title" defaultValue={note.title || "无标题笔记"} aria-label={`重命名 ${note.title || "无标题笔记"}`} className="min-w-0 flex-1 border bg-white px-2 py-1 text-sm" /><button className="border px-2 py-1 text-xs">重命名</button></form><form action={moveNote} className="grid gap-2"><input type="hidden" name="note_id" value={note.id} /><FolderPicker folders={folders} initialFolderId={note.folder_id ?? null} idPrefix={`note-${note.id}`} /><button className="justify-self-start border px-2 py-1 text-xs">移动</button></form></div></details></article>)}</div> : <div className="py-12"><p className="text-lg font-medium">{selectedFolder ? "这个文件夹还是空的" : "从一篇笔记开始"}</p><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-500">日记统一由右上角“今日日记”创建并自动归档到日记文件夹。其他内容可在这里新建为 Markdown 笔记。</p><div className="mt-5"><form action={createNoteInFolder}><input type="hidden" name="folder_id" value={selectedFolder?.id ?? ""} /><button className="border bg-white px-3 py-2 text-sm">新建 Markdown 笔记</button></form></div></div>}</main></div>
  </section>;
}
