import { PageHeader } from "@/components/shared/page-header";
import { CareerNav } from "@/components/career/career-nav";
import { getCareerCapital } from "@/features/career/queries";

export default async function CapitalPage() {
  const data = await getCareerCapital(); const verified = data.facts.filter((fact) => fact.source_document_id || fact.verification_status !== "unverified").length; const approved = data.bullets.filter((bullet) => bullet.status === "approved").length;
  return <><PageHeader title="职业资本" description="只展示已有事实、证据、成果与表达覆盖，不把职业能力压成单一分数。" /><CareerNav current="/career/capital" />
    {data.unavailable ? <p className="mb-6 rounded-[10px] bg-amber-50 px-3.5 py-2.5 text-[12px] leading-5 text-amber-800">Gap Analysis migration 尚未应用，其他职业资本数据仍可查看。</p> : null}
    <div className="grid gap-9 lg:grid-cols-[1fr_1fr]"><section className="space-y-7"><CapitalGroup title="事实与证据" rows={[["已记录事实", data.facts.length], ["有证据或已确认", verified], ["经历", data.experiences.length], ["成果", data.outputs.length]]} /><CapitalGroup title="表达资产" rows={[["已批准表达", approved], ["仍为草稿", data.bullets.length - approved], ["证书", data.certifications.length], ["证书带文件", data.certifications.filter((item) => item.document_id).length]]} /><section><h2 className="text-[14px] font-semibold tracking-[-0.008em] text-[var(--text-primary)]">技能清单</h2><div className="mt-3 divide-y divide-[var(--separator)] border-y border-[var(--separator)]">{data.skills.map((skill) => <div key={skill.id} className="flex min-h-10 items-center justify-between py-2.5 text-[13px]"><span>{skill.name}</span><span className="text-[11px] text-[var(--text-tertiary)]">{skill.category} · {skill.proficiency}</span></div>)}{!data.skills.length ? <p className="py-5 text-[12.5px] text-[var(--text-secondary)]">还没有记录技能。</p> : null}</div></section></section>
      <aside className="border-l border-[var(--separator)] pl-0 lg:pl-7"><h2 className="text-[14px] font-semibold tracking-[-0.008em] text-[var(--text-primary)]">最近 Gap Analysis</h2><div className="mt-3.5 space-y-4">{data.gaps.map((gap) => { const opportunity = Array.isArray(gap.career_opportunities) ? gap.career_opportunities[0] : gap.career_opportunities; return <article key={gap.id} className="border-b border-[var(--separator)] pb-3.5"><p className="text-[13px] font-medium text-[var(--text-primary)]">{opportunity?.role_title || "机会分析"} · {gap.analysis_type === "capital" ? "资本差距" : "简历差距"}</p><p className="mt-1.5 text-[12.5px] leading-5.5 text-[var(--text-secondary)]">{gap.summary}</p><time className="mt-1.5 block text-[11px] tabular-nums text-[var(--text-tertiary)]">{new Date(gap.created_at).toLocaleString("zh-CN")}</time></article>; })}{!data.gaps.length ? <p className="text-[12.5px] leading-5.5 text-[var(--text-secondary)]">在 Opportunities 中录入岗位要求后，可以运行保守、可追溯的差距分析。</p> : null}</div></aside></div></>;
}
function CapitalGroup({ title, rows }: { title: string; rows: [string, number][] }) { return <section><h2 className="text-[14px] font-semibold tracking-[-0.008em] text-[var(--text-primary)]">{title}</h2><dl className="mt-3.5 grid grid-cols-2 gap-x-8 gap-y-4">{rows.map(([label, value]) => <div key={label}><dd className="text-[23px] font-semibold leading-none tracking-[-0.025em] text-[var(--text-primary)]">{value}</dd><dt className="mt-1 text-xs text-zinc-500">{label}</dt></div>)}</dl></section>; }
