import { PageHeader } from "@/components/shared/page-header";
import { CareerNav } from "@/components/career/career-nav";
import { getCareerCapital } from "@/features/career/queries";

export default async function CapitalPage() {
  const data = await getCareerCapital(); const verified = data.facts.filter((fact) => fact.source_document_id || fact.verification_status !== "unverified").length; const approved = data.bullets.filter((bullet) => bullet.status === "approved").length;
  return <><PageHeader title="Career Capital" description="只展示已有事实、证据、成果与表达覆盖，不把职业能力压成单一分数。" /><CareerNav current="/career/capital" />
    {data.unavailable ? <p className="mb-6 border-l-2 border-amber-600 bg-amber-50 px-3 py-3 text-sm text-amber-800">Gap Analysis migration 尚未应用，其他职业资本数据仍可查看。</p> : null}
    <div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><section className="space-y-8"><CapitalGroup title="事实与证据" rows={[["已记录事实", data.facts.length], ["有证据或已确认", verified], ["经历", data.experiences.length], ["成果", data.outputs.length]]} /><CapitalGroup title="表达资产" rows={[["已批准表达", approved], ["仍为草稿", data.bullets.length - approved], ["证书", data.certifications.length], ["证书带文件", data.certifications.filter((item) => item.document_id).length]]} /><section><h2 className="font-medium">技能清单</h2><div className="mt-3 divide-y border-y">{data.skills.map((skill) => <div key={skill.id} className="flex items-center justify-between py-3 text-sm"><span>{skill.name}</span><span className="text-xs text-zinc-500">{skill.category} · {skill.proficiency}</span></div>)}{!data.skills.length ? <p className="py-5 text-sm text-zinc-500">还没有记录技能。</p> : null}</div></section></section>
      <aside className="border-l pl-0 lg:pl-8"><h2 className="font-medium">最近 Gap Analysis</h2><div className="mt-4 space-y-5">{data.gaps.map((gap) => { const opportunity = Array.isArray(gap.career_opportunities) ? gap.career_opportunities[0] : gap.career_opportunities; return <article key={gap.id} className="border-b pb-4"><p className="text-sm font-medium">{opportunity?.role_title || "机会分析"} · {gap.analysis_type === "capital" ? "资本差距" : "简历差距"}</p><p className="mt-2 text-sm leading-6 text-zinc-500">{gap.summary}</p><time className="mt-2 block text-xs text-zinc-400">{new Date(gap.created_at).toLocaleString("zh-CN")}</time></article>; })}{!data.gaps.length ? <p className="text-sm text-zinc-500">在 Opportunities 中录入岗位要求后，可以运行保守、可追溯的差距分析。</p> : null}</div></aside></div></>;
}
function CapitalGroup({ title, rows }: { title: string; rows: [string, number][] }) { return <section><h2 className="font-medium">{title}</h2><dl className="mt-4 grid grid-cols-2 gap-x-8 gap-y-5">{rows.map(([label, value]) => <div key={label}><dd className="text-2xl font-medium">{value}</dd><dt className="mt-1 text-xs text-zinc-500">{label}</dt></div>)}</dl></section>; }
