"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Command, Menu, Plus, Search, Settings, LogOut } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { logoutAction } from "@/features/auth/actions";
const groups=[['总览',[['Today','/today'],['Inbox','/inbox']]],['规划',[['Tasks','/tasks'],['Projects','/projects']]],['知识',[['Notes','/notes'],['Files','/files'],['Photos','/photos']]],['领域',[['Career','/career'],['Investing','/investing']]],['回顾',[['Reviews','/reviews']]]];
export function AppShell({children,email}:{children:React.ReactNode;email:string}){const p=usePathname(),[open,setOpen]=useState(false),[cmd,setCmd]=useState(false);const nav=<nav className="space-y-5">{groups.map(([label,items])=><div key={label as string}><p className="px-3 text-xs text-zinc-500">{label}</p>{(items as string[][]).map(([n,h])=><Link key={h} href={h} onClick={()=>setOpen(false)} className={`mt-1 block rounded-md px-3 py-2 text-sm ${p===h?'bg-[#EDF3F6] text-[#365F78]':'text-zinc-600 hover:bg-white'}`}>{n}{['/files','/photos','/career','/investing','/reviews'].includes(h)&&<span className="ml-2 text-xs text-zinc-400">尚未启用</span>}</Link>)}</div>)}</nav>;return <div className="min-h-screen md:flex"><aside className="hidden w-60 shrink-0 border-r bg-[#F7F7F5] p-4 md:block"><Link href="/today" className="mb-8 block px-3 text-lg font-semibold">Personal OS</Link>{nav}<div className="mt-8 border-t pt-3"><Link href="/settings" className="flex items-center gap-2 px-3 py-2 text-sm"><Settings size={16}/>Settings</Link></div></aside><Dialog open={open} onOpenChange={setOpen}><DialogContent className="left-0 top-0 h-full w-72 translate-x-0 translate-y-0 rounded-none p-4">{nav}</DialogContent></Dialog><main className="min-w-0 flex-1"><header className="flex h-14 items-center justify-between border-b bg-white px-4"><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setOpen(true)} aria-label="打开导航"><Menu/></Button><button onClick={()=>setCmd(true)} className="flex items-center gap-2 text-sm text-zinc-500"><Search size={16}/>搜索 <kbd className="hidden rounded border px-1 text-xs md:inline">⌘K</kbd></button><div className="flex items-center gap-2"><span className="hidden text-xs text-zinc-500 md:inline">同步将在启用后显示</span><Button size="sm" onClick={()=>setCmd(true)}><Plus/>快速创建</Button><form action={logoutAction}><Button variant="ghost" size="icon" aria-label={`${email}，退出`}><LogOut size={16}/></Button></form></div></header><div className="mx-auto max-w-6xl p-5 md:p-8">{children}</div></main><Dialog open={cmd} onOpenChange={setCmd}><DialogContent><div className="flex items-center gap-2 text-sm"><Command size={16}/>Command Palette</div><p className="mt-4 text-sm text-zinc-500">导航、快速创建与搜索将在此统一提供。</p></DialogContent></Dialog></div>}
