import { CareerNav } from "@/components/career/career-nav";
import { Field, PrimaryButton, SelectField, TextField } from "@/components/career/form-controls";
import { createCareerMilestone, createCareerTrack } from "@/features/career/actions";
import { getCareerRoadmap } from "@/features/career/queries";

const start = new Date("2026-08-01T00:00:00+08:00");
const end = new Date("2027-12-31T23:59:59+08:00");
const months = Array.from({ length: 17 }, (_, index) => new Date(2026, 7 + index, 1));
const colors: Record<string, string> = { blue: "bg-[#365f78]", slate: "bg-slate-500", amber: "bg-amber-600", violet: "bg-violet-600", teal: "bg-teal-600" };
function position(date: string) { return Math.max(1, Math.min(99, ((new Date(`${date}T12:00:00+08:00`).getTime() - start.getTime()) / (end.getTime() - start.getTime())) * 100)); }

export default async function CareerRoadmapPage() {
  const { tracks, milestones, directions, unavailable } = await getCareerRoadmap();
  return <><CareerNav current="/career/roadmap" /><header className="mb-7 border-b border-[#e7e5e4] pb-5"><h1 className="text-3xl font-semibold tracking-tight">职业路线</h1><p className="mt-1 text-sm text-zinc-500">把不同方向放入并行泳道，按关键节点推进到 2027 年末。</p></header>
    {unavailable ? <p className="border-l-2 border-amber-600 bg-amber-50 px-3 py-3 text-sm text-amber-800">Career Roadmap 数据库尚未升级。应用 migration 后即可使用。</p> : <><section className="overflow-x-auto border border-[#e7e5e4] bg-white"><div className="min-w-[850px]"><div className="grid grid-cols-[180px_1fr] border-b border-[#e7e5e4]"><div className="px-4 py-3 text-xs font-medium text-zinc-500">路线</div><div className="grid grid-cols-[repeat(17,minmax(0,1fr))]">{months.map((month) => <div key={month.toISOString()} className="border-l border-[#f0eeea] py-3 text-center font-mono text-[10px] text-zinc-500">{month.getFullYear() % 100}.{String(month.getMonth() + 1).padStart(2, "0")}</div>)}</div></div>{tracks.length ? tracks.map((track) => <div key={track.id} className="grid min-h-24 grid-cols-[180px_1fr] border-b border-[#eceae6] last:border-b-0"><div className="border-r border-[#eceae6] px-4 py-4"><p className="text-sm font-medium">{track.name}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-zinc-500">{track.description || ""}</p></div><div className="relative bg-[linear-gradient(to_right,#f1efeb_1px,transparent_1px)] bg-[size:5.882%_100%]">{milestones.filter((item) => item.track_id === track.id).map((item) => <div title={`${item.title} · ${item.target_date}${item.description ? `\n${item.description}` : ""}`} key={item.id} className="absolute top-4 -translate-x-1/2" style={{ left: `${position(item.target_date)}%` }}><span className={`block h-3 w-3 rounded-full ring-4 ring-white ${colors[track.color] || colors.blue}`} /><span className="mt-2 block max-w-24 text-center text-[11px] leading-4 text-zinc-700">{item.title}</span></div>)}</div></div>) : <p className="px-4 py-14 text-center text-sm text-zinc-500">先创建一条路线，再把关键节点排到时间轴上。</p>}</div></section>
      <section className="mt-8 grid gap-8 border-t border-[#e7e5e4] pt-8 lg:grid-cols-2"><form action={createCareerTrack} className="grid gap-3"><h2 className="font-semibold">新建路线</h2><Field label="路线名称" name="name" required placeholder="例如：金融投研与产业资本" /><TextField label="说明（可选）" name="description" /><div className="grid grid-cols-2 gap-3"><SelectField label="状态" name="status" values={["active", "paused"]} defaultValue="active" /><SelectField label="颜色" name="color" values={["blue", "slate", "amber", "violet", "teal"]} defaultValue="blue" /></div><div><PrimaryButton>创建路线</PrimaryButton></div></form><form action={createCareerMilestone} className="grid gap-3"><h2 className="font-semibold">添加关键节点</h2>{tracks.length ? <><SelectField label="所属路线" name="track_id" values={tracks.map((track) => track.id)} /><Field label="节点名称" name="title" required placeholder="例如：完成论文完整初稿" /><TextField label="说明（可选）" name="description" /><Field label="目标日期" name="target_date" type="date" required /><div className="grid grid-cols-2 gap-3"><SelectField label="状态" name="status" values={["planned", "in_progress", "completed", "skipped"]} defaultValue="planned" /><SelectField label="重要程度" name="importance" values={["normal", "high", "low"]} defaultValue="normal" /></div><input type="hidden" name="starts_on" value="" /><select name="career_direction_id" className="border bg-white px-3 py-2 text-sm"><option value="">不关联职业方向</option>{directions.map((direction) => <option key={direction.id} value={direction.id}>{direction.name}</option>)}</select><div><PrimaryButton>添加节点</PrimaryButton></div></> : <p className="text-sm text-zinc-500">先创建至少一条路线。</p>}</form></section></>}
  </>;
}
