"use client";

import { useActionState } from "react";
import { initializeCalendarCategoriesAction, updateCalendarCategoryAiAction, updateCalendarCategoryColorAction, updateCalendarEvent, type CalendarCreateState } from "@/features/calendar/actions";
import type { CalendarCategory } from "@/features/calendar/categories/types";
import { outlookCategoryPalette } from "@/features/calendar/categories/visual";
import { MicrosoftDeviceConnect } from "@/components/calendar/microsoft-device-connect";
import { classifyCalendarEvent } from "@/features/calendar/classification/classifier";
import { getManagedCalendarCategory, primaryCalendarCategories } from "@/features/calendar/classification/taxonomy";
import type { CalendarEventRecord } from "@/features/calendar/types";

const initial: CalendarCreateState = { status: "idle", message: "" };

function CategoryRow({ category }: { category: CalendarCategory }) {
  const [state, action, pending] = useActionState(updateCalendarCategoryColorAction, initial);
  const [aiState, aiAction, aiPending] = useActionState(updateCalendarCategoryAiAction, initial);
  return <div className="border-b py-2 last:border-0"><form action={action} className="grid grid-cols-[minmax(0,1fr)_130px] items-center gap-3">
    <input type="hidden" name="category_id" value={category.id} />
    <div className="min-w-0"><p className="truncate text-sm">{category.display_name}</p><p className="text-[10px] text-zinc-400">{category.category_kind === "external" ? "Outlook 外部分类" : category.category_kind === "context" ? "长期场景" : "主分类"}</p>{state.status === "error" ? <p className="mt-1 text-[10px] text-red-700">{state.message}</p> : null}</div>
    <select name="color" defaultValue={category.color} disabled={pending || !category.provider_category_id} onChange={(event) => event.currentTarget.form?.requestSubmit()} className="h-8 rounded-md border bg-white px-2 text-xs disabled:opacity-50" aria-label={`修改 ${category.display_name} 的颜色`}>
      {Object.entries(outlookCategoryPalette).map(([value, visual]) => <option key={value} value={value}>{visual.label}</option>)}
    </select>
  </form>{category.category_kind !== "external" ? <details className="mt-1"><summary className="cursor-pointer text-[10px] text-zinc-500">AI 分类规则</summary><form action={aiAction} className="mt-2 grid gap-2 rounded-md bg-zinc-50 p-2"><input type="hidden" name="category_id" value={category.id}/><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="ai_enabled" defaultChecked={category.ai_enabled}/>允许 AI 建议此分类</label><label className="grid gap-1 text-[10px] text-zinc-500">说明<input name="ai_description" maxLength={500} defaultValue={category.ai_description ?? ""} className="h-8 rounded border bg-white px-2 text-xs text-zinc-800"/></label><label className="grid gap-1 text-[10px] text-zinc-500">关键词（逗号分隔）<input name="keywords" maxLength={1500} defaultValue={category.keywords.join("，")} className="h-8 rounded border bg-white px-2 text-xs text-zinc-800"/></label><div className="flex items-center gap-2"><button disabled={aiPending} className="rounded border bg-white px-2 py-1 text-[10px] disabled:opacity-50">{aiPending ? "保存中…" : "保存规则"}</button>{aiState.status !== "idle" ? <span className={`text-[10px] ${aiState.status === "error" ? "text-red-700" : "text-[var(--accent)]"}`}>{aiState.message}</span> : null}</div></form></details> : null}</div>;
}

function UnclassifiedRow({ event, categories, timezone }: { event: CalendarEventRecord; categories: CalendarCategory[]; timezone: string }) {
  const suggestion = classifyCalendarEvent(
    { subject: event.subject, description: event.body_text, locationName: event.location_name },
    categories.filter((category) => category.managed_key).map((category) => ({ managed_key: category.managed_key, keywords: category.keywords, ai_enabled: category.ai_enabled })),
  );
  const [state, action, pending] = useActionState(updateCalendarEvent, initial);
  return <form action={action} className="grid gap-2 border-b py-3 last:border-0"><input type="hidden" name="provider_event_id" value={event.provider_event_id}/><input type="hidden" name="original_subject" value={event.subject}/><input type="hidden" name="original_starts_at" value={event.starts_at}/><input type="hidden" name="original_ends_at" value={event.ends_at}/><input type="hidden" name="subject" value={event.subject}/><input type="hidden" name="starts_at" value={event.starts_at}/><input type="hidden" name="ends_at" value={event.ends_at}/><input type="hidden" name="preserve_categories" value="false"/>{suggestion.contextCategoryKeys.map((key) => <input key={key} type="hidden" name="context_category_keys" value={key}/>)}<div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{event.subject || "无标题日程"}</p><p className="mt-0.5 text-[10px] text-zinc-500">{new Intl.DateTimeFormat("zh-CN", { timeZone: timezone, month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(event.starts_at))} · {suggestion.needsConfirmation ? "低置信度，请确认" : suggestion.reason}</p></div><select name="category_choice" defaultValue={suggestion.primaryCategoryKey} className="h-8 w-32 rounded-md border bg-white px-2 text-xs"><option value="__none">不设置分类</option>{primaryCalendarCategories.map((category) => <option key={category.key} value={category.key}>{category.shortName}</option>)}</select></div><div className="flex items-center justify-between"><p className="text-[10px] text-zinc-400">{suggestion.contextCategoryKeys.map((key) => getManagedCalendarCategory(key)?.shortName).filter(Boolean).join(" · ") || "无长期场景"}</p><button disabled={pending || state.status === "success"} className="rounded border px-2 py-1 text-[10px] disabled:opacity-50">{pending ? "写入中…" : state.status === "success" ? "已写入 Outlook" : "确认写入"}</button></div>{state.status === "error" ? <p className="text-[10px] text-red-700">{state.message}</p> : null}</form>;
}

export function CalendarCategoryManager({ categories, timezone, scopeReady, events, referenceTime }: { categories: CalendarCategory[]; timezone: string; scopeReady: boolean; events: CalendarEventRecord[]; referenceTime: number }) {
  const [state, action, pending] = useActionState(initializeCalendarCategoriesAction, initial);
  const now = referenceTime; const horizon = now + 90 * 24 * 60 * 60 * 1000;
  const unclassified = events.filter((event) => !event.categories.length && Date.parse(event.ends_at) >= now && Date.parse(event.starts_at) <= horizon).slice(0, 50);
  if (!scopeReady) return <div><div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm leading-6 text-amber-900">当前 Microsoft 授权缺少 Outlook 分类权限。重新授权后，Personal OS 才能读取、创建和同步 Master Categories。</div><MicrosoftDeviceConnect reconnect /></div>;
  return <div className="grid gap-6"><div className="grid gap-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-medium">Outlook Master Categories</h3><p className="mt-1 text-xs leading-5 text-zinc-500">Personal OS 只管理带有稳定 managed key 的分类，不改名或删除已有外部分类。</p></div><form action={action}><button disabled={pending} className="shrink-0 rounded-md border px-3 py-1.5 text-xs hover:bg-zinc-50 disabled:opacity-50">{pending ? "正在同步…" : "初始化分类"}</button></form></div>{state.status !== "idle" ? <p role="status" className={`text-xs ${state.status === "error" ? "text-red-700" : "text-[var(--accent)]"}`}>{state.message}</p> : null}<div>{categories.length ? categories.map((category) => <CategoryRow key={category.id} category={category} />) : <p className="rounded-md bg-zinc-50 px-3 py-6 text-center text-sm text-zinc-500">尚未同步分类。点击“初始化分类”。</p>}</div></div><section className="border-t pt-5"><div className="flex items-baseline justify-between"><h3 className="text-sm font-medium">整理未分类日程</h3><span className="text-[10px] text-zinc-400">未来 90 天 · {unclassified.length} 项</span></div><p className="mt-1 text-xs leading-5 text-zinc-500">规则只生成建议。每条都必须由你确认后才会 PATCH Outlook。</p><div className="mt-2">{unclassified.length ? unclassified.map((event) => <UnclassifiedRow key={event.id} event={event} categories={categories} timezone={timezone}/>) : <p className="rounded-md bg-zinc-50 px-3 py-5 text-center text-xs text-zinc-500">未来 90 天没有未分类日程。</p>}</div></section></div>;
}
