import { CalendarDays, RefreshCw } from "lucide-react";
import { CalendarCreateForm } from "@/components/calendar/calendar-create-form";
import { MicrosoftDeviceConnect } from "@/components/calendar/microsoft-device-connect";
import { cancelCalendarOperation, confirmCalendarOperation, queueCalendarSync } from "@/features/calendar/actions";
import { getCalendarWorkspace } from "@/features/calendar/queries";

function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { month: "numeric", day: "numeric", weekday: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function operationText(operation: { operation_type: string; payload: unknown }) { const subject = operation.payload && typeof operation.payload === "object" && "subject" in operation.payload ? String(operation.payload.subject) : ""; return operation.operation_type === "sync" ? "刷新 Outlook 日历缓存" : `${operation.operation_type === "create" ? "创建日程" : operation.operation_type} ${subject}`; }

export default async function CalendarPage() {
  const { connection, events, operations, unavailable } = await getCalendarWorkspace();
  if (unavailable) return <section><h1 className="text-2xl font-semibold">Calendar</h1><p className="mt-4 border-l-2 border-red-700 bg-red-50 px-3 py-2 text-sm text-red-800">日历数据库尚未连接。请先应用 Calendar migration。</p></section>;
  return <section className="max-w-5xl"><header className="flex flex-wrap items-start justify-between gap-4 border-b pb-6"><div><p className="text-xs font-medium tracking-wide text-zinc-500">CALENDAR</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Outlook 日历</h1><p className="mt-1 text-sm text-zinc-500">Outlook 是权威来源；此处显示由云端直接同步的未来 14 天缓存。</p></div>{connection ? <form action={queueCalendarSync}><button className="inline-flex items-center gap-1.5 border px-3 py-2 text-sm text-[#365F78]"><RefreshCw size={16} />刷新日历</button></form> : null}</header>
    {!connection || connection.last_error_code === "calendar_not_connected" ? <MicrosoftDeviceConnect reconnect={Boolean(connection)} /> : <><section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><div><h2 className="font-medium">未来日程</h2><div className="mt-3 divide-y border-y">{events.map((event) => <article key={event.id} className="flex gap-3 px-2 py-4"><CalendarDays size={17} className="mt-0.5 shrink-0 text-[#365F78]" /><div className="min-w-0"><h3 className="font-medium">{event.subject || "无标题日程"}</h3><p className="mt-1 text-sm text-zinc-500">{event.is_all_day ? "全天" : `${formatDate(event.starts_at)} — ${formatDate(event.ends_at)}`}{event.location_name ? ` · ${event.location_name}` : ""}</p></div></article>)}{!events.length ? <p className="px-2 py-8 text-sm text-zinc-500">尚未同步到日程。点击“刷新日历”从 Outlook 读取。</p> : null}</div></div><aside className="border-l pl-0 lg:pl-6"><h2 className="font-medium">新建日程</h2><p className="mt-1 text-xs leading-5 text-zinc-500">先创建草稿，再在下方明确确认；确认前不会写入 Outlook。</p><div className="mt-3"><CalendarCreateForm /></div></aside></section><section className="mt-10"><h2 className="font-medium">操作队列</h2><p className="mt-1 text-sm text-zinc-500">只有明确确认的创建请求才会由云端直接发送到 Outlook。</p><div className="mt-3 divide-y border-y">{operations.map((operation) => <article key={operation.id} className="flex flex-wrap items-center justify-between gap-3 px-2 py-3"><div><p className="text-sm font-medium">{operationText(operation)}</p><p className="mt-1 font-mono text-xs text-zinc-500">{operation.status} · {formatDate(operation.requested_at)}{operation.error_code ? ` · ${operation.error_code}` : ""}</p></div>{operation.status === "pending_confirmation" ? <div className="flex gap-2"><form action={confirmCalendarOperation}><input type="hidden" name="operation_id" value={operation.id} /><button className="bg-[#365F78] px-3 py-1.5 text-xs text-white">确认执行</button></form><form action={cancelCalendarOperation}><input type="hidden" name="operation_id" value={operation.id} /><button className="border px-3 py-1.5 text-xs">取消</button></form></div> : operation.status === "queued" ? <form action={cancelCalendarOperation}><input type="hidden" name="operation_id" value={operation.id} /><button className="border px-3 py-1.5 text-xs">取消排队</button></form> : null}</article>)}{!operations.length ? <p className="px-2 py-6 text-sm text-zinc-500">没有待处理操作。</p> : null}</div></section><div className="mt-6 border-l-2 border-zinc-300 pl-3 text-xs leading-5 text-zinc-500"><p>云端连接 {connection.label} · 已授权 {connection.oauth_connected_at ? formatDate(connection.oauth_connected_at) : "未知"} · 上次同步 {connection.last_sync_at ? formatDate(connection.last_sync_at) : "从未"}</p>{connection.last_error_code ? <p className="mt-1">最近错误：{connection.last_error_code}</p> : null}</div></>}</section>;
}
