import "server-only";
import type { requireOwner } from "@/lib/auth/require-owner";
import type { ProactiveInsight } from "./types";
type Supabase = Awaited<ReturnType<typeof requireOwner>>["supabase"];
export async function reconcileProactiveInsights(supabase: Supabase, userId: string, insights: ProactiveInsight[], now = new Date()) {
  const active = new Set(insights.map((item)=>item.fingerprint)); const {data:unresolved}=await supabase.from("proactive_events").select("id,fingerprint").is("resolved_at",null); const stale=(unresolved??[]).filter((item)=>!active.has(item.fingerprint)); if(stale.length) await supabase.from("proactive_events").update({resolved_at:now.toISOString(),resolution_reason:"condition_cleared"}).in("id",stale.map((item)=>item.id));
  const {data:currentInsights}=await supabase.from("proactive_insights").select("id,fingerprint").is("dismissed_at",null); const expired=(currentInsights??[]).filter((item)=>!active.has(item.fingerprint)); if(expired.length) await supabase.from("proactive_insights").update({effective_until:now.toISOString()}).in("id",expired.map((item)=>item.id));
  for(const insight of insights){const until=new Date(now.getTime()+36*36e5).toISOString();const {data:event,error:eventError}=await supabase.from("proactive_events").upsert({user_id:userId,event_type:insight.kind,fingerprint:insight.fingerprint,severity:insight.priority,occurred_at:now.toISOString(),effective_until:until,payload:{title:insight.title,description:insight.description??null},last_detected_at:now.toISOString(),resolved_at:null,resolution_reason:null},{onConflict:"user_id,fingerprint"}).select("id").single();if(eventError||!event)continue;const {data:saved,error:insightError}=await supabase.from("proactive_insights").upsert({user_id:userId,insight_type:insight.kind,fingerprint:insight.fingerprint,severity:insight.priority,title:insight.title,description:insight.description??null,href:insight.href,effective_until:until},{onConflict:"user_id,fingerprint"}).select("id").single();if(insightError||!saved)continue;await supabase.from("proactive_insight_events").upsert({insight_id:saved.id,event_id:event.id},{onConflict:"insight_id,event_id"});}
}
