import { CheckCircle2, RefreshCw } from "lucide-react";
import { MicrosoftDeviceConnect } from "@/components/calendar/microsoft-device-connect";
import { completeMicrosoftTodoTaskAction, syncMicrosoftTodoAction } from "@/features/tasks/microsoft-todo";
import { getMicrosoftTodoWorkspace } from "@/features/tasks/queries";

export default async function Tasks() {
  const { connection, lists, tasks, unavailable, schemaMissing } = await getMicrosoftTodoWorkspace();
  const listNames = new Map(lists.map((list) => [list.id, list.display_name]));
  const active = tasks.filter((task) => task.status !== "completed");
  const completed = tasks.filter((task) => task.status === "completed");
  if (unavailable) return <section><h1 className="text-2xl font-semibold">Tasks</h1><p className="mt-4 border-l-2 border-red-700 bg-red-50 px-3 py-2 text-sm text-red-800">无法读取 Microsoft To Do 缓存。请检查数据库连接。</p></section>;
  return <section className="max-w-5xl"><header className="flex flex-wrap items-start justify-between gap-4 border-b pb-6"><div><p className="text-xs font-medium tracking-wide text-zinc-500">PLANNING</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Tasks</h1><p className="mt-1 text-sm text-zinc-500">Microsoft To Do 是权威来源；此处是云端同步的私人工作视图。</p></div>{connection && !schemaMissing ? <form action={syncMicrosoftTodoAction}><button className="inline-flex items-center gap-1.5 border px-3 py-2 text-sm text-[#365F78]"><RefreshCw size={16} />刷新 To Do</button></form> : null}</header>{schemaMissing ? <p className="mt-6 border-l-2 border-amber-600 bg-amber-50 px-3 py-2 text-sm text-amber-800">Microsoft To Do 数据库尚未升级。部署后请应用本次 migration，才能同步任务。</p> : null}{!connection || connection.last_error_code === "calendar_not_connected" ? <MicrosoftDeviceConnect reconnect={Boolean(connection)} /> : <>{!schemaMissing && !lists.length ? <section className="mt-6 border-l-2 border-[#365F78] bg-[#EDF3F6] px-4 py-4"><h2 className="font-medium">为 Microsoft To Do 补充授权</h2><p className="mt-1 text-sm leading-6 text-zinc-600">现有 Outlook 日历连接需要重新授权一次，以授予 Tasks.ReadWrite。完成后点击“刷新 To Do”。</p><MicrosoftDeviceConnect reconnect /></section> : null}<section className="mt-6"><div className="flex items-baseline justify-between border-b pb-3"><h2 className="font-medium">待完成</h2><span className="font-mono text-xs text-zinc-500">{active.length}</span></div><div className="divide-y">{active.map((task) => <article key={task.id} className="flex gap-3 py-4"><form action={completeMicrosoftTodoTaskAction}><input type="hidden" name="task_id" value={task.id} /><button aria-label={`完成 ${task.title}`} className="mt-0.5 text-zinc-400 hover:text-[#365F78]"><CheckCircle2 size={18} /></button></form><div className="min-w-0"><h3 className="text-sm font-medium">{task.title || "无标题任务"}</h3>{task.body_text ? <p className="mt-1 whitespace-pre-wrap text-sm text-zinc-500">{task.body_text}</p> : null}<p className="mt-2 text-xs text-zinc-400">{listNames.get(task.todo_list_id) || "Microsoft To Do"}{task.due_at ? ` · 截止 ${new Date(task.due_at).toLocaleDateString("zh-CN")}` : ""}{task.importance === "high" ? " · 高优先级" : ""}</p></div></article>)}{!active.length ? <p className="py-8 text-sm text-zinc-500">没有待完成任务。点击“刷新 To Do”读取 Microsoft To Do。</p> : null}</div></section>{completed.length ? <section className="mt-8"><h2 className="border-b pb-3 font-medium">已完成</h2><div className="divide-y">{completed.slice(0, 20).map((task) => <p key={task.id} className="py-3 text-sm text-zinc-400 line-through">{task.title || "无标题任务"}</p>)}</div></section> : null}</>}</section>;
}
