import { PageHeader } from "@/components/shared/page-header";
import { CareerNav } from "@/components/career/career-nav";
import { createResumeVersion, finalizeResumeVersion, setResumeVersionBullets } from "@/features/career/actions";
import { getResumeVersions } from "@/features/career/queries";

export default async function ResumesPage() {
  const data = await getResumeVersions();
  return <><PageHeader title="Resume Center" description="简历是职业事实的版本化投影；投递记录永远保留当时使用的版本。" /><CareerNav current="/career/resumes" />
    {data.unavailable ? <p className="mb-6 border-l-2 border-amber-600 bg-amber-50 px-3 py-3 text-sm text-amber-800">Resume Version migration 尚未应用。</p> : null}
    <details className="mb-8 border-b pb-6"><summary className="cursor-pointer text-sm font-medium text-[#365F78]">+ 新建简历版本</summary><form action={createResumeVersion} className="mt-5 grid gap-4 md:grid-cols-3"><Field name="title" label="名称 *" required/><Field name="version_label" label="版本标签"/><label className="grid gap-1 text-sm"><span>目标方向</span><select name="target_direction_id" className="border bg-white px-3 py-2"><option value="">通用</option>{data.directions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm md:col-span-3"><span>固定内容（Markdown，可选）</span><textarea name="content_markdown" className="min-h-32 border bg-white px-3 py-2"/></label><button className="w-fit bg-[#365F78] px-3 py-2 text-sm text-white">创建草稿</button></form></details>
    <div className="space-y-8">{data.resumes.map((resume) => { const selected = new Set(data.links.filter((link) => link.resume_version_id === resume.id).map((link) => link.bullet_id)); const usage = data.applications.filter((item) => item.resume_version_id === resume.id).length; return <article key={resume.id} className="border-t pt-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium">{resume.title}</h2><p className="mt-1 text-xs text-zinc-500">{resume.version_label || "未命名版本"} · 更新于 {new Date(resume.updated_at).toLocaleString("zh-CN")} · {usage} 次申请引用</p></div><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs">{resume.status === "approved" ? "已定稿" : "草稿"}</span></div>{resume.content_markdown ? <p className="mt-4 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-zinc-600">{resume.content_markdown}</p> : null}<details className="mt-5"><summary className="cursor-pointer text-sm text-[#365F78]">编排已批准表达 · {selected.size}</summary><form action={setResumeVersionBullets} className="mt-4 space-y-3"><input type="hidden" name="resume_id" value={resume.id}/>{data.bullets.map((bullet) => { const experience = Array.isArray(bullet.experiences) ? bullet.experiences[0] : bullet.experiences; return <label key={bullet.id} className="flex items-start gap-3 text-sm"><input type="checkbox" name="bullet_id" value={bullet.id} defaultChecked={selected.has(bullet.id)} className="mt-1"/><span><span className="text-xs text-zinc-400">{experience?.organization || "经历"} · </span>{bullet.content}</span></label>; })}{!data.bullets.length ? <p className="text-sm text-zinc-500">没有已批准表达。先从经历事实中创建并批准表达，AI 草稿不能直接进入最终简历。</p> : <button disabled={resume.status !== "draft"} className="border px-3 py-2 text-sm disabled:opacity-40">保存编排</button>}</form></details>{resume.status === "draft" ? <form action={finalizeResumeVersion} className="mt-5 border-t pt-4"><input type="hidden" name="resume_id" value={resume.id}/><button className="text-sm font-medium text-[#365F78]">定稿此版本</button><p className="mt-1 text-xs text-zinc-400">定稿后请新建版本继续修改，保证历史投递可追溯。</p></form> : null}</article>; })}</div>{!data.resumes.length ? <div className="py-20 text-center"><p className="font-medium">还没有简历版本</p><p className="mt-2 text-sm text-zinc-500">创建草稿，选择已由你批准且有事实依据的表达。</p></div> : null}</>;
}
function Field({ name, label, required = false }: { name: string; label: string; required?: boolean }) { return <label className="grid gap-1 text-sm"><span>{label}</span><input name={name} required={required} className="border bg-white px-3 py-2"/></label>; }
