"use client";

import { useActionState, useState } from "react";
import { generateNoteAiSuggestion, type NoteAiState } from "@/features/notes/ai-actions";

const initialState: NoteAiState = { status: "idle", message: "", suggestion: "" };

export function NoteAiAssistant({ noteId, title, bodyMarkdown, onInsert }: { noteId: string; title: string; bodyMarkdown: string; onInsert: (text: string) => void }) {
  const [instruction, setInstruction] = useState("");
  const [state, formAction, pending] = useActionState(generateNoteAiSuggestion, initialState);
  const choose = (value: string) => setInstruction(value);
  return <section className="mt-5 border-t pt-4"><div className="flex items-baseline justify-between gap-3"><div><p className="text-xs font-medium tracking-wide text-zinc-500">AI · DEEPSEEK</p><h2 className="mt-1 text-sm font-medium">笔记助手</h2></div><p className="text-xs text-zinc-500">仅处理此刻提交的本篇内容</p></div><form action={formAction} className="mt-3 space-y-2"><input type="hidden" name="note_id" value={noteId} /><input type="hidden" name="title" value={title} /><input type="hidden" name="body_markdown" value={bodyMarkdown} /><div className="flex flex-wrap gap-2"><button type="button" onClick={() => choose("请用不超过五条要点总结这篇笔记。")} className="border px-2 py-1 text-xs">总结</button><button type="button" onClick={() => choose("请提炼行动项，按 Markdown 任务列表输出；没有明确行动项时说明原因。")} className="border px-2 py-1 text-xs">提炼行动</button><button type="button" onClick={() => choose("请在不改变事实与语气的前提下，润色这篇笔记。仅输出润色后的正文。")} className="border px-2 py-1 text-xs">润色</button></div><textarea name="instruction" value={instruction} onChange={(event) => setInstruction(event.target.value)} required maxLength={2000} rows={2} className="w-full resize-y border bg-white px-3 py-2 text-sm leading-5" placeholder="告诉 AI 如何协助这篇笔记…" /><button disabled={pending || !bodyMarkdown.trim()} className="bg-[#365F78] px-3 py-2 text-xs text-white disabled:opacity-60">{pending ? "正在生成…" : "生成建议"}</button>{!bodyMarkdown.trim() ? <p className="text-xs text-zinc-500">先写一点内容，再让 AI 协助。</p> : null}</form>{state.status !== "idle" ? <p role="status" className={`mt-3 text-xs ${state.status === "error" ? "text-red-700" : "text-[#365F78]"}`}>{state.message}</p> : null}{state.suggestion ? <div className="mt-3 border-l-2 border-[#365F78] bg-[#EDF3F6] p-3"><pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-zinc-700">{state.suggestion}</pre><button type="button" onClick={() => onInsert(state.suggestion)} className="mt-3 border border-[#365F78] bg-white px-2 py-1 text-xs text-[#365F78]">插入到正文末尾</button></div> : null}</section>;
}
