"use client";

import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { createExperience } from "@/features/career/actions";

export function CreateExperienceDialog() {
  const [open, setOpen] = useState(false);
  const [, action, pending] = useActionState(async (_: null, formData: FormData) => { await createExperience(formData); return null; }, null);
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button>新增经历</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>新增真实经历</DialogTitle><DialogDescription>先记录发生过什么；成果、事实和求职表达可在详情页逐步补充。</DialogDescription></DialogHeader><form action={action} className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm"><span>组织、学校或项目 *</span><input required name="organization" className="border bg-white px-3 py-2" /></label><label className="grid gap-1 text-sm"><span>角色</span><input name="role" className="border bg-white px-3 py-2" /></label><label className="grid gap-1 text-sm"><span>类别</span><select name="experience_type" defaultValue="internship" className="border bg-white px-3 py-2"><option value="education">教育经历</option><option value="internship">实习经历</option><option value="project">项目经历</option><option value="campus">校园经历</option><option value="research">研究经历</option><option value="volunteer">志愿经历</option><option value="employment">工作经历</option><option value="other">其他</option></select></label><label className="grid gap-1 text-sm"><span>地点</span><input name="location" className="border bg-white px-3 py-2" /></label><label className="grid gap-1 text-sm"><span>开始日期</span><input name="start_date" type="date" className="border bg-white px-3 py-2" /></label><label className="grid gap-1 text-sm"><span>结束日期</span><input name="end_date" type="date" className="border bg-white px-3 py-2" /></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input name="is_current" type="checkbox" /> 当前仍在进行</label><label className="grid gap-1 text-sm sm:col-span-2"><span>背景（可选）</span><textarea name="background_markdown" className="min-h-24 border bg-white px-3 py-2" /></label><input type="hidden" name="department" value="" /><input type="hidden" name="raw_description_markdown" value="" /><input type="hidden" name="confidentiality_level" value="private" /><input type="hidden" name="status" value="draft" /><div className="sm:col-span-2"><Button disabled={pending}>{pending ? "正在创建…" : "创建并继续补充"}</Button></div></form></DialogContent></Dialog>;
}
