"use client";

import { useState, useTransition } from "react";
import { abandonPurchaseItem, extendPurchaseCooldown, markPurchaseItemPurchased, setPurchaseNecessity } from "@/features/shopping/actions";

type Item = { id: string; title: string; price_cny: number | null; necessity: string; necessity_confirmed: boolean; status: string; cooldown_until: string | null; reason_to_buy: string | null; existing_alternative: string | null; source_url: string | null };
export function ShoppingItemDetail({ item }: { item: Item }) {
  const [current, setCurrent] = useState(item); const [message, setMessage] = useState(""); const [pending, start] = useTransition();
  const ready = current.status === "ready" || (current.status === "cooling" && current.cooldown_until && new Date(current.cooldown_until) <= new Date());
  const run = (next: Item, action: () => Promise<void>) => { const before = current; setCurrent(next); setMessage(""); start(async () => { try { await action(); } catch { setCurrent(before); setMessage("操作失败，已恢复原状态。"); } }); };
  const decide = (necessity: "necessary" | "nonessential") => { const canBuy = necessity === "necessary" && (current.price_cny ?? Infinity) <= 50; run({ ...current, necessity, necessity_confirmed: true, status: canBuy ? "ready" : "cooling", cooldown_until: canBuy ? null : new Date(Date.now() + 7 * 86_400_000).toISOString() }, () => setPurchaseNecessity(current.id, necessity, current.price_cny)); };
  return <section className="max-w-2xl space-y-6"><header><p className="text-xs tracking-[.15em] text-[var(--accent)]">{ready ? "READY" : current.status.toUpperCase()}</p><h1 className="mt-2 text-3xl font-semibold">{current.title}</h1><p className="mt-2 text-lg">{current.price_cny === null ? "价格未知" : `¥${current.price_cny}`}</p></header><div className="space-y-4 rounded-lg border bg-white p-5"><div><p className="text-xs text-[var(--text-tertiary)]">为什么想买</p><p>{current.reason_to_buy || "未填写"}</p></div><div><p className="text-xs text-[var(--text-tertiary)]">已有替代品</p><p>{current.existing_alternative || "未填写"}</p></div>{current.necessity === "unknown" ? <div><p>这是必要品吗？</p><p className="mt-1 text-xs text-[var(--text-tertiary)]">AI 的判断不能代替你的确认。</p><div className="mt-3 flex gap-2"><button disabled={pending} onClick={() => decide("necessary")} className="rounded border px-3 py-2 text-sm">必要</button><button disabled={pending} onClick={() => decide("nonessential")} className="rounded border px-3 py-2 text-sm">非必要</button></div></div> : null}{ready ? <div><p className="font-medium">现在可以重新决定了</p><div className="mt-3 flex gap-2"><button disabled={pending} onClick={() => run({ ...current, status: "purchased", cooldown_until: null }, () => markPurchaseItemPurchased(current.id))} className="rounded bg-[var(--accent)] px-3 py-2 text-sm text-white">我买了</button><button disabled={pending} onClick={() => run({ ...current, status: "cooling", cooldown_until: new Date(Date.now() + 7 * 86_400_000).toISOString() }, () => extendPurchaseCooldown(current.id))} className="rounded border px-3 py-2 text-sm">再等 7 天</button><button disabled={pending} onClick={() => run({ ...current, status: "abandoned", cooldown_until: null }, () => abandonPurchaseItem(current.id))} className="rounded border px-3 py-2 text-sm">不买了</button></div></div> : current.status === "cooling" ? <p className="text-sm text-[var(--text-secondary)]">可重新考虑：{new Date(current.cooldown_until!).toLocaleString("zh-CN")}</p> : null}{message ? <p role="alert" className="text-sm text-red-700">{message}</p> : null}{current.source_url ? <a href={current.source_url} target="_blank" rel="noreferrer" className="text-sm text-[var(--accent)]">打开商品链接</a> : null}</div></section>;
}
