"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { createPurchaseItem } from "@/features/shopping/actions";

type Item = { id: string; title: string; price_cny: number | null; status: string; cooldown_until: string | null; category: string | null; necessity: string };
export function ShoppingWorkspace({ items, stats: _stats, initialCreateOpen }: { items: Item[]; stats: { active: number; ready: number; purchased: number }; initialCreateOpen: boolean }) {
  void _stats;
  const [creating, setCreating] = useState(initialCreateOpen); const [pending, start] = useTransition(); const [rows, setRows] = useState(items); const [error, setError] = useState("");
  const ready = rows.filter((item) => item.status === "ready" || (item.status === "cooling" && item.cooldown_until && new Date(item.cooldown_until) <= new Date()));
  const cooling = rows.filter((item) => item.status === "cooling" && (!item.cooldown_until || new Date(item.cooldown_until) > new Date()));
  const submit = (form: FormData) => {
    const tempId = `optimistic-${crypto.randomUUID()}`;
    const title = String(form.get("title") || "").trim(); const price = Number(form.get("priceCny")); const necessary = form.get("necessity") === "necessary" && form.get("necessityConfirmed") === "on";
    const optimistic: Item = { id: tempId, title, price_cny: Number.isFinite(price) && String(form.get("priceCny") || "") ? price : null, category: null, necessity: String(form.get("necessity") || "unknown"), status: necessary && Number.isFinite(price) && price <= 50 ? "ready" : "cooling", cooldown_until: necessary && Number.isFinite(price) && price <= 50 ? null : new Date(Date.now() + 7 * 86_400_000).toISOString() };
    setRows((current) => [optimistic, ...current]); setCreating(false); setError("");
    start(async () => { try { const created = await createPurchaseItem(form); setRows((current) => current.map((item) => item.id === tempId ? { ...optimistic, id: created.id } : item)); } catch { setRows((current) => current.filter((item) => item.id !== tempId)); setError("保存失败，待购项目未创建。请稍后重试。"); } });
  };
  const currentStats = { active: rows.filter((item) => !["purchased", "abandoned"].includes(item.status)).length, ready: ready.length, purchased: rows.filter((item) => item.status === "purchased").length };
  return <section className="space-y-8"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium tracking-[.16em] text-[var(--text-tertiary)]">SHOPPING</p><h1 className="mt-2 text-2xl font-semibold">想买不等于现在要买。</h1><p className="mt-2 text-sm text-[var(--text-secondary)]">默认等待；必要且不超过 ¥50 才允许立即购买。</p></div><button onClick={() => setCreating(true)} className="rounded-md bg-[var(--accent)] px-3 py-2 text-sm text-white">加入待购</button></header>{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<div className="grid grid-cols-3 gap-3">{[["待购", currentStats.active], ["可决定", currentStats.ready], ["已购买", currentStats.purchased]].map(([label, value]) => <div key={String(label)} className="rounded border bg-white p-3"><p className="text-xs text-[var(--text-tertiary)]">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>{creating ? <form action={submit} className="grid gap-3 rounded-lg border bg-white p-4 sm:grid-cols-2"><input name="title" required placeholder="想买什么？" className="rounded border px-3 py-2"/><input name="priceCny" type="number" min="0" step="0.01" placeholder="价格（元，可选）" className="rounded border px-3 py-2"/><select name="necessity" className="rounded border px-3 py-2"><option value="unknown">还没决定是否必要</option><option value="necessary">必要品</option><option value="nonessential">非必要品</option></select><label className="flex items-center gap-2 text-sm"><input name="necessityConfirmed" type="checkbox"/> 我确认这是必要品</label><textarea name="reasonToBuy" placeholder="为什么想买（可选）" className="min-h-20 rounded border p-3 sm:col-span-2"/><div className="flex gap-2"><button disabled={pending} className="rounded bg-[var(--accent)] px-3 py-2 text-sm text-white">保存</button><button type="button" onClick={() => setCreating(false)} className="px-3 py-2 text-sm">取消</button></div></form> : null}<ItemSection title="Needs Decision" items={ready}/><ItemSection title="Cooling" items={cooling}/><ItemSection title="All" items={rows}/></section>;
}
function ItemSection({ title, items }: { title: string; items: Item[] }) { return <section><h2 className="mb-3 text-sm font-medium text-[var(--text-secondary)]">{title}</h2><div className="divide-y rounded-lg border bg-white">{items.length ? items.map((item) => item.id.startsWith("optimistic-") ? <div key={item.id} className="flex items-center justify-between gap-4 px-4 py-3 opacity-70"><div><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-[var(--text-tertiary)]">正在保存…</p></div><span className="text-sm tabular-nums">{item.price_cny === null ? "价格未知" : `¥${item.price_cny}`}</span></div> : <Link key={item.id} href={`/shopping/${item.id}`} className="flex items-center justify-between gap-4 px-4 py-3 hover:bg-[var(--surface-hover)]"><div><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-[var(--text-tertiary)]">{item.category || "未分类"} · {item.status.toUpperCase()}</p></div><span className="text-sm tabular-nums">{item.price_cny === null ? "价格未知" : `¥${item.price_cny}`}</span></Link>) : <p className="px-4 py-5 text-sm text-[var(--text-tertiary)]">暂无项目。</p>}</div></section>; }
