"use server";
import { revalidatePath } from "next/cache";
import { requireOwner } from "@/lib/auth/require-owner";
import { graphLinkSchema, type GraphEntityType } from "./types";

const tables: Record<GraphEntityType, string> = { experience: "experiences", note: "notes", document: "documents", todo_task: "microsoft_todo_tasks", calendar_event: "calendar_events", career_direction: "career_directions", career_milestone: "career_milestones", career_track: "career_tracks", project: "projects" };
async function ensureOwned(supabase: Awaited<ReturnType<typeof requireOwner>>["supabase"], type: GraphEntityType, id: string) { const { data, error } = await supabase.from(tables[type]).select("id").eq("id", id).is("archived_at", null).maybeSingle(); if (error || !data) throw new Error("找不到关联对象或无权访问。"); }
export async function createGraphLink(input: unknown) { const value = graphLinkSchema.parse(input); if (value.source.type === value.target.type && value.source.id === value.target.id) throw new Error("不能关联到自身。"); const { supabase, userId } = await requireOwner(); await Promise.all([ensureOwned(supabase, value.source.type, value.source.id), ensureOwned(supabase, value.target.type, value.target.id)]); const { error } = await supabase.from("entity_links").upsert({ user_id: userId, source_type: value.source.type, source_id: value.source.id, target_type: value.target.type, target_id: value.target.id, relationship_type: "related", created_via: value.createdVia, metadata: value.metadata }, { onConflict: "user_id,source_type,source_id,target_type,target_id,relationship_type" }); if (error) throw new Error("关联未能保存，请稍后重试。"); revalidatePath(`/career/experiences/${value.source.id}`); }
export async function dismissGraphSuggestion(input: unknown) { const value = graphLinkSchema.pick({ source: true, target: true }).parse(input); const { supabase, userId } = await requireOwner(); const { error } = await supabase.from("entity_link_dismissals").upsert({ user_id: userId, source_type: value.source.type, source_id: value.source.id, target_type: value.target.type, target_id: value.target.id }); if (error) throw new Error("无法忽略此建议。"); revalidatePath(`/career/experiences/${value.source.id}`); }
