import { requireOwner } from "@/lib/auth/require-owner";
import { searchPersonalOs } from "@/features/search/queries";
import { graphEntityDefinitions, type GraphEntityType } from "./types";

type Resolved = { id: string; type: GraphEntityType; title: string; href: string; relationshipType: string };
const href = (type: GraphEntityType, id: string) => type === "note" ? `/notes/${id}` : type === "experience" ? `/career/experiences/${id}` : type === "career_milestone" || type === "career_track" ? "/career/roadmap" : type === "career_direction" ? "/career/directions" : type === "career_opportunity" ? "/career/opportunities" : type === "career_application" ? "/career/applications" : type === "resume_version" ? "/career/resumes" : type === "review" ? "/reviews" : type === "document" ? "/files" : type === "todo_task" ? "/tasks" : type === "calendar_event" ? "/calendar" : "/projects";
const tableByType: Record<GraphEntityType, { table: string; title: string }> = { experience: { table: "experiences", title: "organization,role" }, note: { table: "notes", title: "title" }, document: { table: "documents", title: "title,original_filename" }, todo_task: { table: "microsoft_todo_tasks", title: "title" }, calendar_event: { table: "calendar_events", title: "subject" }, career_direction: { table: "career_directions", title: "name" }, career_milestone: { table: "career_milestones", title: "title" }, career_track: { table: "career_tracks", title: "name" }, career_opportunity: { table: "career_opportunities", title: "organization,role_title" }, career_application: { table: "career_applications", title: "status" }, resume_version: { table: "resume_versions", title: "title" }, review: { table: "reviews", title: "title" }, project: { table: "projects", title: "name" } };
function entityTitle(type: GraphEntityType, row: Record<string, unknown>) { if (type === "experience") return [row.organization, row.role].filter(Boolean).join(" · "); if (type === "career_opportunity") return [row.organization, row.role_title].filter(Boolean).join(" · "); if (type === "career_application") return `申请 · ${String(row.status ?? "未命名")}`; return String(row.title ?? row.name ?? row.subject ?? row.original_filename ?? "未命名"); }
export async function getExperienceGraph(experienceId: string, label: string) { const { supabase } = await requireOwner(); const { data: links } = await supabase.from("entity_links").select("source_type,source_id,target_type,target_id,relationship_type").or(`and(source_type.eq.experience,source_id.eq.${experienceId}),and(target_type.eq.experience,target_id.eq.${experienceId})`).is("archived_at", null); const others = (links ?? []).map((link) => link.source_id === experienceId ? { type: link.target_type as GraphEntityType, id: link.target_id, relationshipType: link.relationship_type } : { type: link.source_type as GraphEntityType, id: link.source_id, relationshipType: link.relationship_type }).filter((item) => item.type in tableByType);
  const grouped = new Map<GraphEntityType, string[]>(); others.forEach((item) => grouped.set(item.type, [...(grouped.get(item.type) ?? []), item.id])); const names = new Map<string, string>(); await Promise.all([...grouped].map(async ([type, ids]) => { const def = tableByType[type]; const { data } = await supabase.from(def.table).select(`id,${def.title}`).in("id", ids).is("archived_at", null); (data as unknown as Array<Record<string, unknown>> ?? []).forEach((row) => names.set(`${type}:${row.id}`, entityTitle(type, row))); }));
  const related: Resolved[] = others.flatMap((item) => { const title = names.get(`${item.type}:${item.id}`); return title ? [{ ...item, title, href: href(item.type, item.id) }] : []; });
  const existing = new Set(related.map((item) => `${item.type}:${item.id}`)); const { data: dismissed } = await supabase.from("entity_link_dismissals").select("target_type,target_id").eq("source_type", "experience").eq("source_id", experienceId); (dismissed ?? []).forEach((item) => existing.add(`${item.target_type}:${item.target_id}`)); const candidates = await searchPersonalOs({ query: label, limit: 8 }); const suggestions = candidates.filter((item) => item.entityType in graphEntityDefinitions && item.entityType !== "experience" && !existing.has(`${item.entityType}:${item.entityId}`)).slice(0, 4).map((item) => ({ type: item.entityType as GraphEntityType, id: item.entityId, title: item.title, href: item.href, reason: `搜索结果与「${label}」相关` }));
  return { related, suggestions };
}
