"use client";

import { useState } from "react";
import { removeDeepSeekKey, saveDeepSeekKey } from "@/features/ai/actions";

type Settings = { model: "deepseek-v4-flash" | "deepseek-v4-pro"; default_event_duration_minutes: number; updated_at: string } | null;

export function DeepSeekSettingsForm({ configured, settings, timezone }: { configured: boolean; settings: Settings; timezone: string }) {
  const [editing, setEditing] = useState(!configured);
  const model = settings?.model || "deepseek-v4-pro";
  const duration = settings?.default_event_duration_minutes || 30;
  return <section className="border-b pb-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-medium">AI · DeepSeek</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">API Key 只在提交时通过加密连接发送到服务端，之后不会显示或返回浏览器。Calendar 助手会获得当前时间与时区（{timezone}），能直接理解“明天”“下周”等自然语言。</p>{configured && !editing ? <p className="mt-2 text-xs text-[#365F78]">已配置 · {model === "deepseek-v4-pro" ? "V4 Pro（更智能）" : "V4 Flash（更快）"} · 默认时长 {duration} 分钟 · 更新于 {settings ? new Date(settings.updated_at).toLocaleDateString("zh-CN") : "未知"}</p> : null}</div>{configured && !editing ? <div className="flex gap-2"><button type="button" className="border px-3 py-2 text-sm" onClick={() => setEditing(true)}>调整设置</button><form action={removeDeepSeekKey}><button className="border px-3 py-2 text-sm">移除</button></form></div> : null}</div>{editing ? <form action={saveDeepSeekKey} className="mt-4 grid max-w-xl gap-3"><label className="grid gap-1 text-sm">DeepSeek API Key<input name="api_key" type="password" autoComplete="off" required={!configured} minLength={20} maxLength={500} placeholder={configured ? "留空则保持当前 Key" : "粘贴 DeepSeek API Key"} className="border bg-white px-3 py-2 text-sm" /></label><label className="grid gap-1 text-sm">模型<select name="model" defaultValue={model} className="border bg-white px-3 py-2 text-sm"><option value="deepseek-v4-pro">V4 Pro · 更强的日期理解与规划能力</option><option value="deepseek-v4-flash">V4 Flash · 更快、更节省</option></select></label><label className="grid gap-1 text-sm">未说明结束时间时的默认日程时长<select name="default_event_duration_minutes" defaultValue={String(duration)} className="border bg-white px-3 py-2 text-sm">{[15, 30, 45, 60, 90, 120].map((minutes) => <option key={minutes} value={minutes}>{minutes} 分钟</option>)}</select></label><div className="flex gap-2"><button className="bg-[#365F78] px-3 py-2 text-sm text-white">加密保存</button>{configured ? <button type="button" className="border px-3 py-2 text-sm" onClick={() => setEditing(false)}>取消</button> : null}</div></form> : null}</section>;
}
